commercetools/test-data

.github/workflows/main.yml, .yarnrc, babel.config.js, core/package.json, core/src/builder.spec.js, core/src/builder.spec.ts, core/src/builder.ts, core/src/generator.ts, core/src/helpers.ts, core/src/index.ts, core/src/transformer.ts, core/src/transforms.spec.js, core/src/transforms.spec.ts, core/src/types.ts, core/tsconfig.declarations.json, jest.test.config.js, package.json, rollup.config.js, tsconfig.json, yarn.lock
I've got it to a point where the types compile and the autocompletion is helpful.
There is still some cleanup to do, but the tests work (the same as we have internally) and this is a good sign :)
=> Add core package with TS declarations

core/package.json, core/src/builder.spec.ts, core/src/builder.ts, core/src/helpers.ts, core/src/index.ts, core/src/transformer.ts, core/src/types.ts
Removes some types complexity that was not strictly necessary.
=> refactor: simplify types

.changeset/config.json, package.json, yarn.lock
See https://github.com/atlassian/changesets/pull/458
=> refactor(changeset): use globs for linked packages

babel.config.js, package.json, rollup.config.js, yarn.lock
Just to keep things consistent.
=> Rollup and Babel improvements

jest.eslint.config.js, jest.test.config.js, package.json, yarn.lock
=> refactor(jest): remove jest-watch-master plugin

.changeset/light-guests-train.md, core/src/transformer.ts, models/commons/src/index.ts, models/commons/src/initiator/README.md, models/commons/src/initiator/builder.spec.ts, models/commons/src/initiator/builder.ts, models/commons/src/initiator/generator.ts, models/commons/src/initiator/index.ts, models/commons/src/initiator/presets/index.ts, models/commons/src/initiator/transformers.ts, models/commons/src/initiator/types.ts, models/commons/src/reference/builder.spec.ts, models/commons/src/reference/builder.ts, models/commons/src/reference/generator.ts, models/commons/src/reference/index.ts, models/commons/src/reference/presets/category-reference.spec.ts, models/commons/src/reference/presets/category-reference.ts, models/commons/src/reference/presets/index.ts, models/commons/src/reference/transformers.ts, models/commons/src/reference/types.ts
I want to eventually add `Product` and `ProductType`, both of which need Initiator and Reference respectively.
=> feat(commons): add `Reference` and `Initiator`

.changeset/unlucky-glasses-appear.md, LICENSE, core/LICENSE, models/category/LICENSE, models/channel/LICENSE, models/commons/LICENSE, utils/LICENSE
Just to test the "fixed" release mode.
=> chore: update license year to 2022

.changeset/little-squids-beg.md, models/category/package.json, models/channel/package.json, models/commons/package.json, yarn.lock
Still for testing the "fixed" mode.
=> chore: update platform-sdk deps

.changeset/fifty-masks-sell.md, .changeset/old-trees-dream.md, .changeset/red-ladybugs-destroy.md, core/src/helpers.ts, models/category/src/builder.spec.ts, models/category/src/transformers.ts, models/category/src/types.ts, models/channel/src/builder.spec.ts, models/channel/src/generator.ts, models/channel/src/transformers.ts, models/channel/src/types.ts, models/commons/src/address/transformers.ts, models/commons/src/client-logging/transformers.ts, models/commons/src/localized-string/helpers.ts, models/commons/src/localized-string/index.ts, models/commons/src/localized-string/transformers.ts
=> fix: graphql props overwrites

.changeset/slimy-points-boil.md, LICENSE, core/LICENSE, models/attribute-plain-enum-value/LICENSE, models/category/LICENSE, models/cent-precision-money/LICENSE, models/channel/LICENSE, models/commons/LICENSE, models/customer/LICENSE, models/money/LICENSE, models/product-discount-value-absolute/LICENSE, models/product-discount-value-external/LICENSE, models/product-discount-value-relative/LICENSE, models/tax-category/LICENSE, models/tax-rate/LICENSE, models/zone/LICENSE, utils/LICENSE
Does what the title says. A little housekeeping
~~Do we need to changeset this?~~
=> chore(test-data): remove dates from license files

.changeset/gold-plants-share.md, models/product-catalog-data/LICENSE, models/product-catalog-data/README.md, models/product-catalog-data/package.json, models/product-catalog-data/src/builder.spec.ts, models/product-catalog-data/src/builder.ts, models/product-catalog-data/src/generator.ts, models/product-catalog-data/src/index.ts, models/product-catalog-data/src/presets/index.ts, models/product-catalog-data/src/transformers.ts, models/product-catalog-data/src/types.ts, pnpm-lock.yaml
Adds the `product-catalog-data` model.
=> feat: add product-catalog-data model

.changeset/neat-planets-battle.md, models/product-type/LICENSE, models/product-type/README.md, models/product-type/package.json, models/product-type/src/builder.spec.ts, models/product-type/src/builder.ts, models/product-type/src/generator.ts, models/product-type/src/index.ts, models/product-type/src/presets/index.ts, models/product-type/src/product-type-draft/builder.spec.ts, models/product-type/src/product-type-draft/builder.ts, models/product-type/src/product-type-draft/generator.ts, models/product-type/src/product-type-draft/index.ts, models/product-type/src/product-type-draft/presets/index.ts, models/product-type/src/product-type-draft/transformers.ts, models/product-type/src/transformers.ts, models/product-type/src/types.ts, pnpm-lock.yaml, yarn.lock
Adds the `product-type` and `product-type-draft` models.
=> Fct 183 sample data product type

pnpm-lock.yaml
This PR installs the deps using pnpm v8 and then I will update the value on package.json
Once that's done, I will work on merging these because they are related I think
https://github.com/commercetools/test-data/pull/180
https://github.com/commercetools/test-data/pull/168
=> chore: update pnpm to v8 - Part I

package.json
=> chore: update pnpm to v8 - Part II

.changeset/sharp-ads-crash.md, models/product-discount/package.json, models/product-discount/src/product-discount-draft/presets/empty.spec.ts, models/product-discount/src/product-discount-draft/presets/empty.ts, models/product-discount/src/product-discount-draft/presets/index.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-dresses.spec.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-dresses.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-kids.spec.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-kids.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-pants.spec.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/discount-pants.ts, models/product-discount/src/product-discount-draft/presets/sample-data-fashion/index.ts, pnpm-lock.yaml
This PR creates product discount presets, guided by [this data](https://github.dev/commercetools/test-data-research/blob/6d2d1fa5babc37b0abbccf474c6fd6490f029db6/src/entity-drafts/product-discounts.ts#L2)
=> chore(test-data): create `ProductDiscount` presets

models/attribute-definition/src/types.ts, models/category/src/types.ts, models/product-type/src/types.ts, models/product/src/product/types.ts
This PR is an extension of [this PR](https://github.com/commercetools/test-data/pull/256), apologies for the branch-sandwich here. Just resolving some additional type inconsistencies so we can cast to the correct types in our resolver.
=> chore(test-data): additional type changes

.changeset/stale-seas-admire.md, models/attribute-type/src/attribute-enum-type/attribute-enum-type-draft/builder.spec.ts, models/attribute-type/src/attribute-enum-type/attribute-enum-type-draft/transformers.ts, models/attribute-type/src/attribute-enum-type/types.ts, models/product-type/src/product-type-draft/presets/sample-data-fashion/accessories.spec.ts, models/product-type/src/product-type-draft/presets/sample-data-fashion/dresses.spec.ts, models/product-type/src/product-type-draft/presets/sample-data-fashion/jackets.spec.ts, models/product-type/src/product-type-draft/presets/sample-data-fashion/pants.spec.ts, models/product-type/src/product-type-draft/presets/sample-data-fashion/shirts.spec.ts
I missed this field in my last PR 😬
=> chore(test-data): fix missing `values` field in `AttributeEnumTypeDraft`

.changeset/kind-falcons-laugh.md, models/payment/README.md, models/payment/src/index.ts, models/payment/src/transaction/builder.spec.ts, models/payment/src/transaction/builder.ts, models/payment/src/transaction/constants.ts, models/payment/src/transaction/generator.ts, models/payment/src/transaction/index.ts, models/payment/src/transaction/presets/index.ts, models/payment/src/transaction/transaction-draft/builder.spec.ts, models/payment/src/transaction/transaction-draft/builder.ts, models/payment/src/transaction/transaction-draft/generator.ts, models/payment/src/transaction/transaction-draft/index.ts, models/payment/src/transaction/transaction-draft/presets/index.ts, models/payment/src/transaction/transaction-draft/transformers.ts, models/payment/src/transaction/transformers.ts, models/payment/src/transaction/types.ts
This PR adds the `Transaction` and `TransactionDraft` models.
=> FCT-457: Transaction and Transaction Draft Models 

models/payment/README.md, models/payment/package.json, models/payment/src/index.ts, models/payment/src/payment/builder.spec.ts, models/payment/src/payment/builder.ts, models/payment/src/payment/generator.ts, models/payment/src/payment/index.ts, models/payment/src/payment/payment-draft/builder.spec.ts, models/payment/src/payment/payment-draft/builder.ts, models/payment/src/payment/payment-draft/generator.ts, models/payment/src/payment/payment-draft/index.ts, models/payment/src/payment/payment-draft/presets/index.ts, models/payment/src/payment/payment-draft/transformers.ts, models/payment/src/payment/presets/index.ts, models/payment/src/payment/transformers.ts, models/payment/src/payment/types.ts, pnpm-lock.yaml
WIP: This PR adds the `Payment` and `PaymentDraft` models.
Reviewers: a few notes/questions inline.
=> feat(models): add payment and payment draft models

.changeset/ninety-cobras-protect.md, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus1.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus2.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-usa.ts, models/payment/src/transaction/constants.ts, models/payment/src/transaction/generator.ts, models/payment/src/transaction/transaction-draft/generator.ts
This PR updates the `Transaction` constants to camelcase.
=> FCT-451: transaction const update

.changeset/poor-moose-applaud.md, models/store/src/store/store-draft/presets/empty.spec.ts, models/store/src/store/store-draft/presets/empty.ts, models/store/src/store/store-draft/presets/index.ts, models/store/src/store/store-draft/presets/sample-data-fashion/index.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-01.spec.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-01.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-02.spec.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-02.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-03.spec.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-03.ts
- Add fashion sample presets for Stores
=> feat(stores): add fashion sample presets

.changeset/slow-squids-yawn.md, models/tax-category/src/tax-category/tax-category-draft/presets/index.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/eu-tax-category.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/eu-tax-category.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/eu2-tax-category.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/eu2-tax-category.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/index.ts
Added tax category presets for Good Store data
=> feat(tax category): added presets for goodstore data

.changeset/big-waves-cough.md, models/inventory-entry/LICENSE, models/inventory-entry/README.md, models/inventory-entry/package.json, models/inventory-entry/src/builder.spec.ts, models/inventory-entry/src/builder.ts, models/inventory-entry/src/generator.ts, models/inventory-entry/src/index.ts, models/inventory-entry/src/inventory-entry-draft/builder.spec.ts, models/inventory-entry/src/inventory-entry-draft/builder.ts, models/inventory-entry/src/inventory-entry-draft/generator.ts, models/inventory-entry/src/inventory-entry-draft/index.ts, models/inventory-entry/src/inventory-entry-draft/presets/index.ts, models/inventory-entry/src/inventory-entry-draft/transformers.ts, models/inventory-entry/src/presets/index.ts, models/inventory-entry/src/transformers.ts, models/inventory-entry/src/types.ts, pnpm-lock.yaml
This PR adds the InventoryEntry and InventoryEntryDraft models.
=> FCT-493: InventoryEntry

.changeset/sweet-horses-scream.md, models/channel/src/channel-draft/presets/index.ts, models/channel/src/channel-draft/presets/sample-data-goodstore/index.ts, models/channel/src/channel-draft/presets/sample-data-goodstore/inventory-channel.spec.ts, models/channel/src/channel-draft/presets/sample-data-goodstore/inventory-channel.ts, models/channel/src/channel-draft/presets/sample-data-goodstore/product-distribution.spec.ts, models/channel/src/channel-draft/presets/sample-data-goodstore/product-distribution.ts
Adding channel presets for the Good Store data. The channels were renamed to provide a more logical description. 
https://commercetools.atlassian.net/jira/software/c/projects/FCT/boards/362?modal=detail&selectedIssue=FCT-500
=> feat(channel): added channel presets for goodstore data

.changeset/blue-wolves-know.md, models/product-discount/src/product-discount/product-discount-draft/presets/index.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/index.ts
Added product discount presets to the goodstore data. 
https://docs.google.com/spreadsheets/d/1ehbT8iThVOmS3WdE_3a1eTNlCsSYCVoSOSd1X8hAMDw/edit#gid=1247651259
=> feat(product discount): added presets for goodstore data

.changeset/wise-icons-sparkle.md, models/payment/src/payment/index.ts, models/payment/src/payment/payment-draft/presets/index.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/index.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/jennifer-jones-payment.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/jennifer-jones-payment.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/sebastian-mueller-payment.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/sebastian-mueller-payment.ts
This PR adds Sample Data GoodStore payment draft presets.
=> Fct 515 goodstore payment presets

.changeset/fast-pugs-walk.md, models/product-type/README.md, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/builder.spec.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/builder.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/generator.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/index.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/presets/index.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/transformers.ts, models/product-type/src/attribute-reference-type/builder.spec.ts, models/product-type/src/attribute-reference-type/builder.ts, models/product-type/src/attribute-reference-type/constants.ts, models/product-type/src/attribute-reference-type/generator.ts, models/product-type/src/attribute-reference-type/index.ts, models/product-type/src/attribute-reference-type/presets/index.ts, models/product-type/src/attribute-reference-type/transformers.ts, models/product-type/src/attribute-reference-type/types.ts, models/product-type/src/index.ts
- Created `AttributeReferenceType` and draft models
=> feat(models/product-type): add `AttributeReferenceType` and `AttributeReferenceTypeDraft` models

.changeset/sour-planes-bow.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/index.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/index.ts, models/discount-code/src/discount-code-draft/presets/index.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/index.ts
This PR is an un-forked clone of [this PR](https://github.com/commercetools/test-data/pull/358)
=> chore(test-data): goodstore cart discount and discount code presets

models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.ts
This PR fixes an incorrect product preset
=> chore(test-data): fix incorrect product preset type

.changeset/early-dodos-scream.md, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/builder.spec.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/generator.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/transformers.ts, models/product-type/src/attribute-localized-enum-type/types.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/builder.spec.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/generator.ts, models/product-type/src/attribute-reference-type/attribute-reference-type-draft/transformers.ts, models/product-type/src/attribute-reference-type/types.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/builder.spec.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/generator.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/transformers.ts, models/product-type/src/attribute-set-type/types.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.spec.ts
@stephsprinkle identified some issues with our transformation for these attribute draft models, this PR fixes them ✨
=> bug(test-data): corrections to lenum, set, and reference transformations

.changeset/poor-scissors-pull.md, models/category/src/category-draft/presets/index.ts, models/commons/src/address/address-draft/presets/index.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/jennifer-jones.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/jennifer-robinson.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/jennifer-schmidt.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/sebastian-franklin.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/sebastian-muller.ts, models/customer/src/customer-draft/presets/sample-data-goodstore/sebastian-smith.ts
This PR unifies the exported presets directory name to `sampleDataGoodStore`.
=> Fct fix goodstore exports

.changeset/sour-walls-act.md
Forgot a changeset from the previous PR, missed some packages
=> chore(test-data): new changeset

.changeset/hungry-chefs-behave.md, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.ts
Standard shipping is default shipping (we had two default shipping methods)
=> chore(test-data): fix shipping method defaults

.changeset/lovely-foxes-type.md, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.ts
This PR deactivates product discounts based on performance bottlenecks we are still experiencing
=> chore(test-data): deactivate good store product discounts

.changeset/green-knives-learn.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.ts
=> chore(test-data): reactivate goodstore discount presets

.changeset/ten-socks-sparkle.md, models/payment/src/payment/index.ts
This PR removes an unnecessary export that broke our resolver.
=> Fct payment presets fix

models/shopping-list/LICENSE, models/shopping-list/README.md, models/shopping-list/package.json, models/shopping-list/src/builder.spec.ts, models/shopping-list/src/builder.ts, models/shopping-list/src/generator.ts, models/shopping-list/src/index.ts, models/shopping-list/src/presets/index.ts, models/shopping-list/src/shopping-list-draft/builder.spec.ts, models/shopping-list/src/shopping-list-draft/builder.ts, models/shopping-list/src/shopping-list-draft/generator.ts, models/shopping-list/src/shopping-list-draft/index.ts, models/shopping-list/src/shopping-list-draft/presets/index.ts, models/shopping-list/src/shopping-list-draft/transformers.ts, models/shopping-list/src/transformers.ts, models/shopping-list/src/types.ts, pnpm-lock.yaml
This PR consists of a new ShoppingList folder with the following models:
ShoppingList/ ShoppingListDraft
=> PANGOLIN-3183 - New package for model: `ShoppingList`

.changeset/tasty-gifts-raise.md, models/custom-view/src/custom-view-permission-draft/builder.spec.ts, models/custom-view/src/custom-view-permission-draft/builder.ts, models/custom-view/src/custom-view-permission-draft/generator.ts, models/custom-view/src/custom-view-permission-draft/index.ts, models/custom-view/src/custom-view-permission-draft/presets/index.ts, models/custom-view/src/custom-view-permission-draft/presets/manage-only-permissions.ts, models/custom-view/src/custom-view-permission-draft/presets/presets.spec.ts, models/custom-view/src/custom-view-permission-draft/presets/view-only-permissions.ts, models/custom-view/src/custom-view-permission-draft/transformers.ts, models/custom-view/src/custom-view-permission-draft/types.ts, models/custom-view/src/custom-view-permission/presets/view-only-permissions.ts, models/custom-view/src/custom-view/custom-view-draft/generator.ts, models/custom-view/src/index.ts
This PR introduces a customViewPermissionDraft model.
=> Add model for custom-view-permission-draft

.changeset/honest-frogs-join.md, models/product-type/src/product-type/presets/index.ts, models/product-type/src/product-type/presets/milk.spec.js, models/product-type/src/product-type/presets/milk.ts, models/product/src/product-catalog-data/presets/happy-cow-milk-product-catalog-data.ts, models/product/src/product-catalog-data/presets/index.ts, models/product/src/product-data/presets/happy-cow-milk-product-data.ts, models/product/src/product-data/presets/index.ts, models/product/src/product-variant/presets/happy-cow-milk-master-variant.ts, models/product/src/product-variant/presets/index.ts, models/product/src/product/presets/happy-cow-milk.ts, models/product/src/product/presets/index.ts
This PR creates the preset which is used in MC FE. It is required to migrate this [ticket](https://commercetools.atlassian.net/browse/PCM-3508)
=> PCM-3508: add preset for happy cow milk product

.changeset/pretty-eggs-kiss.md, models/commons/src/key-reference/key-reference-draft/presets/index.ts, models/commons/src/key-reference/key-reference-draft/presets/product-type-reference.spec.ts, models/commons/src/key-reference/key-reference-draft/presets/shipping-method-reference.spec.ts, models/commons/src/key-reference/key-reference-draft/presets/staged-quote-reference.spec.ts, models/commons/src/key-reference/key-reference-draft/presets/staged-quote-reference.ts, models/commons/src/key-reference/key-reference-draft/presets/tax-category-reference.spec.ts
=> chore(td): create staged quote KeyReferenceDraft preset

.changeset/nine-bulldogs-stare.md, models/product/src/product/product-draft/presets/index.ts
=> chore(td): fix productDraft preset exports

.changeset/tasty-scissors-complain.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-b2b/tower-cranes-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-b2b/tower-cranes-bogo.ts
=> chore(presets): fix predicate

.changeset/plenty-hairs-remember.md, .changeset/popular-crabs-push.md, models/associate-role/src/associate-role-draft/builder.ts, models/associate-role/src/associate-role-draft/presets/sample-data-b2b/admin.spec.ts, models/associate-role/src/associate-role-draft/presets/sample-data-b2b/approver.spec.ts, models/associate-role/src/associate-role-draft/presets/sample-data-b2b/buyer.spec.ts, models/custom-object/src/custom-object-draft/builder.ts
=> chore(test-data): fix associate role preset transformations

.changeset/cool-avocados-raise.md, models/tax-category/src/tax-rate/generator.ts, models/tax-category/src/tax-rate/tax-rate-draft/generator.ts
fix(faker warnings): use recommended object destructure syntax for pa…ssing args in faker.finance.amount method in tax-rate generators
=> Fix warnings for faker.finance.amount

.changeset/light-tigers-confess.md, models/store/src/store/store-draft/presets/sample-data-b2b/de-fr-uk.ts, models/store/src/store/store-draft/presets/sample-data-b2b/default-store.ts, models/store/src/store/store-draft/presets/sample-data-b2b/spain.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-large-customers.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-medium-customers.ts, models/store/src/store/store-draft/transformers.ts
add ps build field to store transformer, build productselections correctly
=> Fct 783 add ps to stores

.changeset/little-carpets-destroy.md, models/discount-code/src/discount-code-draft/presets/sample-data-b2b/bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-b2b/bogo.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts
Remove app limit and increase customer limit to 5 for BOGO discounts
=> [FCT-812] Sample Data - BoGo Discount to be Applied Multiple Times

.gitignore
Trying to fix issue of updating to pnpm v9.
=> fix(pnpm): to link-workspace-package (v9 defaults to false)

.gitignore, .npmrc
=> fix: add npmrc for pnpm v9

models/cart-discount/src/cart-discount-value-absolute/builder.spec.ts, models/cart-discount/src/cart-discount-value-absolute/transformers.ts, models/cart-discount/src/cart-discount-value-absolute/types.ts, models/cart-discount/src/cart-discount-value-fixed/builder.spec.ts, models/cart-discount/src/cart-discount-value-fixed/transformers.ts, models/cart-discount/src/cart-discount-value-fixed/types.ts, models/cart-discount/src/cart-discount-value-gift-line-item/builder.spec.ts, models/cart-discount/src/cart-discount-value-gift-line-item/transformers.ts, models/cart-discount/src/cart-discount-value-gift-line-item/types.ts, models/cart-discount/src/cart-discount-value-relative/builder.spec.ts, models/cart-discount/src/cart-discount-value-relative/transformers.ts, models/cart-discount/src/cart-discount-value-relative/types.ts
Align MC cardDiscount types with the tests
this will be a canary realize.
=> Ma aling   typename with mc types names

.changeset/cuddly-socks-compete.md
for the changes added to the cart discount model adding 
add disctributionChannelRef and supplyChanelRef to discunt value gift line item test data in the fraphQl response 
we need to publish the changes of previos PR https://github.com/commercetools/test-data/pull/579
=> feat: bump

.changeset/twelve-garlics-poke.md, models/product/src/product-catalog-data/presets/boring-generic-milk-product-catalog-data.ts, models/product/src/product-catalog-data/presets/index.ts, models/product/src/product-data/presets/boring-generic-milk-product-data.ts, models/product/src/product-data/presets/index.ts, models/product/src/product-variant/presets/boring-generic-milk-master-variant.ts, models/product/src/product-variant/presets/index.ts, models/product/src/product/presets/boring-generic-milk.ts, models/product/src/product/presets/index.ts, pnpm-lock.yaml
This PR adds preset for the boring generic milk.
=> chore: add preset for boring generic milk

.changeset/hot-guests-peel.md, models/discount-code/src/builder.spec.ts, models/discount-code/src/transformers.ts, models/discount-code/src/types.ts
This PR builds by default the `applicationCount` prop of DiscountCode.
It's a prop that Priceless is already using in Discounts app.
=> feat: build `applicationCount` property of GraphQL `DiscountCode` type

.changeset/young-eels-share.md, .github/CODEOWNERS, models/filter-values/LICENSE, models/filter-values/README.md, models/filter-values/package.json, models/filter-values/src/builder.spec.ts, models/filter-values/src/builder.ts, models/filter-values/src/generator.ts, models/filter-values/src/index.ts, models/filter-values/src/presets/index.ts, models/filter-values/src/transformers.ts, models/filter-values/src/types.ts, pnpm-lock.yaml
Adds new package `@commercetools-test-data/filter-values` with `FilterValues` data model (MC Settings).
=> feat: add `FilterValues` test data model

.changeset/hip-balloons-suffer.md, models/discounts-custom-view/LICENSE, models/discounts-custom-view/README.md, models/discounts-custom-view/package.json, models/discounts-custom-view/src/builder.spec.ts, models/discounts-custom-view/src/builder.ts, models/discounts-custom-view/src/discounts-custom-view-input/builder.spec.ts, models/discounts-custom-view/src/discounts-custom-view-input/builder.ts, models/discounts-custom-view/src/discounts-custom-view-input/generator.ts, models/discounts-custom-view/src/discounts-custom-view-input/index.ts, models/discounts-custom-view/src/discounts-custom-view-input/presets/index.ts, models/discounts-custom-view/src/discounts-custom-view-input/transformers.ts, models/discounts-custom-view/src/generator.ts, models/discounts-custom-view/src/index.ts, models/discounts-custom-view/src/presets/index.ts, models/discounts-custom-view/src/transformers.ts, models/discounts-custom-view/src/types.ts, models/filter-values/README.md, models/filter-values/src/generator.ts, pnpm-lock.yaml
Adds new package @commercetools-test-data/discounts-custom-view with DiscountsCustomView and DiscountsCustomViewInput data model (MC Settings).
=> feat: add DiscountsCustomView and DiscountsCustomViewInput test data model

.changeset/happy-pants-lie.md
Adds changeset for https://github.com/commercetools/test-data/pull/625 😞
=> fix(attribute-enum-type): add changeset

.changeset/tender-news-kick.md, models/standalone-price/src/staged-standalone-price/builder.spec.ts, models/standalone-price/src/staged-standalone-price/builder.ts, models/standalone-price/src/staged-standalone-price/generator.ts, models/standalone-price/src/staged-standalone-price/index.ts, models/standalone-price/src/staged-standalone-price/presets/index.ts, models/standalone-price/src/staged-standalone-price/transformers.ts, models/standalone-price/src/staged-standalone-price/types.ts
This PR is part of our bigger plan to replace the custom test-data models in the StandalonePrice repo
=> feat(): add StagedStandalonePrice model

.changeset/silent-colts-hunt.md, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-sets.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-sets.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/modern-upholstered-twin-bed-03.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/modern-upholstered-twin-bed-03.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/rumi-chair-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/rumi-chair-01.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed-01.ts, models/product/src/product/product-draft/presets/sample-data-b2c-lifestyle/modern-upholstered-twin-bed.spec.ts, models/product/src/product/product-draft/presets/sample-data-b2c-lifestyle/rumi-chair.spec.ts, models/product/src/product/product-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed.spec.ts
Necessary fixes for the B2C Sample Date Import attributes.
=> fix(product-attributes): fix for sample data import

.changeset/lovely-bats-march.md, .changeset/silent-bulldogs-drum.md, .changeset/silver-cats-play.md, models/product-type/src/attribute-definition/builder.spec.ts, models/product-type/src/attribute-definition/transformers.ts, models/product-type/src/attribute-definition/types.ts, models/product-type/src/product-type/transformers.ts, models/product/package.json, models/product/src/attribute/generator.ts, models/product/src/product-catalog-data/builder.spec.ts, models/product/src/product-data/builder.spec.ts, models/product/src/product-data/generator.ts, models/product/src/product-data/transformers.ts, pnpm-lock.yaml
Fixes three minor issues, can be reviewed commit by commit.
Would enable migration on this PR: https://github.com/commercetools/merchant-center-frontend/pull/17463
=> FEC-66: fixes for product type and product data models

models/business-unit/src/associate-role-assignment/associate-role-assignment-draft/builder.ts, models/business-unit/src/associate/associate-draft/builder.ts, models/business-unit/src/company/builder.ts, models/business-unit/src/division/builder.ts, models/commons/src/key-reference/key-reference-draft/builder.ts, models/commons/src/localized-string/localized-string-draft/builder.ts, models/commons/src/price-tier/price-tier-draft/builder.ts, models/commons/src/price/builder.ts, models/commons/src/reference/reference-draft/builder.ts, models/type/src/type/builder.spec.ts
I found some lint errors in the main branch related to import order in some files.
This small PR fixes those imports so we can fix the main branch build.
=> Fix lintin import erors

.changeset/afraid-pianos-push.md, models/type/src/index.ts
export field type from type model
=> chore: export field type from type model

.github/CODEOWNERS
As agreed with the test automation engineers, this pull request updates the `CODEOWNERS` file to include their gitHub team so the are notified about changes in this repository.
=> Notify test automation engineers about changes in the repository

generators/src/new-test-model/new-test-model.generator.ts, generators/src/new-test-model/templates/model/builders.spec.tpl, generators/src/new-test-model/templates/model/builders.tpl, generators/src/new-test-model/templates/model/fields-config.tpl, generators/src/new-test-model/templates/model/index.tpl, generators/src/new-test-model/templates/model/presets/example-preset/example-preset.tpl, generators/src/new-test-model/templates/model/presets/index.tpl, generators/src/new-test-model/templates/model/types.tpl
In this PR we include two main improvements:
* The CLI will ask the user if they want to generate a preset example for the new model
* The CLI will ask the user if the new model requires a draft and will generate its files if needed
https://github.com/user-attachments/assets/5bf238a9-71cf-4d85-a549-3f4ea50dfc04
=> [FEC-197] New test data models CLI improvements

.changeset/nine-buses-smile.md, models/product/package.json, models/product/src/product-catalog-data/types.ts, models/product/src/product/types.ts, pnpm-lock.yaml
`TProductGraphql` and `TProductCatalogDataGraphql` were using some REST types.
=> fix(product): `TProductGraphql` and `TProductCatalogDataGraphql` types

.changeset/big-moons-sink.md, models/product/src/product-data/builders.spec.ts, models/product/src/product-data/fields-config.ts
=> fix(product): rest representation of categoryOrderHints is an object, not an array

models/channel/src/channel-draft/builder.spec.ts
=> fix: wrong import path

README.md
This Pull Request aims to define clear expectation towards ownership and governance within this repository.
=> Add ownership and governance to readme

.changeset/tame-cats-yawn.md, standalone/src/models/cart-discount/cart-discount-custom-line-items-target/types.ts, standalone/src/models/cart-discount/index.ts
Added missing import for `cart-discount-custom-line-items-target` in `index.js`
=> chore: added missing import for cart-discount-custom-line-items-target model

.changeset/ninety-candles-press.md, standalone/src/models/commons/price/types.ts, standalone/src/models/standalone-price/types.ts
This PR updates SP and Price models with the right (temporary) types for recurrence policy
=> Adjust Price Models types for recurrence policy

.changeset/yummy-glasses-wear.md
This PR includes the missing changeset file I forgot to include in this PR: #872
=> Add missing changeset

.changeset/wise-feet-jog.md, standalone/src/models/my-view/index.ts, standalone/src/models/my-view/quotes-list-view/builders.spec.ts, standalone/src/models/my-view/quotes-list-view/builders.ts, standalone/src/models/my-view/quotes-list-view/fields-config.ts, standalone/src/models/my-view/quotes-list-view/index.ts, standalone/src/models/my-view/quotes-list-view/presets/index.ts, standalone/src/models/my-view/quotes-list-view/types.ts
Adds missing QuotesListView model.
=> feat(my-view): add quotes-list-view model

.changeset/three-melons-give.md, standalone/src/models/my-view/business-units-list-view/builders.spec.ts, standalone/src/models/my-view/business-units-list-view/builders.ts, standalone/src/models/my-view/business-units-list-view/fields-config.ts, standalone/src/models/my-view/business-units-list-view/index.ts, standalone/src/models/my-view/business-units-list-view/presets/index.ts, standalone/src/models/my-view/business-units-list-view/types.ts, standalone/src/models/my-view/index.ts
Adds missing BusinessUnitsListView model.
=> FEC-276: add business units list my view model

.changeset/red-laws-yawn.md, standalone/src/models/my-view/business-units-list-view/builders.spec.ts, standalone/src/models/my-view/business-units-list-view/fields-config.ts
This PR fixes the typename of BusinessUnitsListMyView
=> fix: to fix business unit my view model typename
