commercetools/test-data

.changeset/real-donkeys-trade.md, core/src/builder.spec.ts, core/src/transformer.ts, core/src/types.ts
We started implementing some models in appkit (https://github.com/commercetools/merchant-center-application-kit/pull/1743) and bumped into some small issues.
This PR fixes that.
=> fix(core): transformer types, replaceFields option takes higher precedence now

.changeset/shy-suits-cover.md, babel.config.js
To compile for example optional chaining and so on.
=> fix: bundles compat with browser environments

.changeset/strong-candles-clean.md, models/commons/src/localized-string/builder.spec.ts, models/commons/src/localized-string/transformers.ts
LocalizedString can't have an undefined as it's translation value, but we use it in some cases to override one created by `random()` builder (e.g. `LocalizedString.presets().empty`). That leads to warnings in tests, using such test data.
This PR fixes this by filtering out empty translations in transform step.
=> fix(localized-string): filter out empty translations

.changeset/quick-eagles-notice.md, core/src/builder.spec.ts, core/src/builder.ts, core/src/generator.ts, core/src/types.ts, models/commons/src/localized-string/builder.ts, models/commons/src/localized-string/types.ts
As we collected some experience with using test-data, it's turned out people never use an option to provide `defaults` prop to `Builder` instance, which current implementation provides, because facilities provided by `generator` prop are just enough. So, in order to shrink the API surface a bit, we decided to drop this prop (https://github.com/commercetools/test-data/issues/23). 
Apart from mentioned above, this PR reorganizes how `Builder` invokes the provided generator internally. Namely, there is no reason to wait for `buildXXX` or setter function to be invoked and generation can be performed right away. Which simplifies code a bit.
=> feat: drop `defaults` prop from builder

.changeset/ten-waves-obey.md, core/package.json, models/commons/package.json, package.json, yarn.lock
https://github.com/preconstruct/preconstruct/releases/tag/%40preconstruct%2Fcli%402.0.0
I run `yarn preconstruct fix`
=> chore: upgrade to preconstruct v2

.changeset/nervous-pumpkins-obey.md, core/package.json, core/src/@jackfranklin/test-data-bot/README.md, core/src/@jackfranklin/test-data-bot/index.spec.ts, core/src/@jackfranklin/test-data-bot/index.ts, core/src/builder.spec.ts, core/src/generator.ts, core/src/index.ts, models/commons/package.json, models/commons/src/initiator/generator.ts, models/commons/src/reference/generator.ts, package.json, yarn.lock
Given that `@jackfranklin/test-data-bot` seems unmaintained and still uses `faker` v4, I decided to drop its dependency and include the source code directly here, so that we can use `faker` v5 at our own pace.
We also had the workaround with the types (https://github.com/jackfranklin/test-data-bot/pull/344).
So essentially, we can now ship `faker` v5.
=> refactor: use faker v5

.changeset/shaggy-falcons-hug.md, models/commons/package.json, models/commons/src/reference/builder.spec.ts, models/commons/src/reference/transformers.ts, models/commons/src/reference/types.ts
- Correct `ExpandedRest` and `ExpandedGraphql` shapes.
Previous implementation implied that both types exposed the same shape: 
```
{
id: string
typeId: string
obj: {}
}
```
which is not the case.
I introduced now `Versioned` which is simply a "unified" object that includes `id` and maybe `version` to clarify that this object is used to pass into `obj`
=> fix(commons/reference): distinguish expanded rest reference and graphql

.changeset/giant-crabs-pull.md, models/category/LICENSE, models/category/README.md, models/category/index.ts, models/category/package.json, models/category/src/builder.spec.ts, models/category/src/builder.ts, models/category/src/generator.ts, models/category/src/index.ts, models/category/src/presets/index.ts, models/category/src/transformers.ts, models/category/src/types.ts, package.json, utils/LICENSE, utils/README.md, utils/index.ts, utils/package.json, utils/src/create-related-dates.ts, utils/src/index.ts
- introduces new package `@commercetools-test-data/utils` to export some helpers
- adds `models/category`
=> Add `models/category`

.changeset/smart-ways-yawn.md, core/src/builder.spec.ts, core/src/helpers.ts, core/src/types.ts
- Closes https://github.com/commercetools/test-data/issues/85
The exact `__typename` on any list within all services and parts of GraphQL schemas of the CT can't be inferred by `${name}QueryResult`. 
As a solution, I propose to have an explicit `typename` overwrite. Over time we could even argue to remove the `name` altogether.
Closes https://github.com/commercetools/test-data/issues/85.
=> feat(core): to add typename support to graphql list building

.changeset/modern-bulldogs-sell.md, core/README.md, core/package.json, core/src/@jackfranklin/test-data-bot/index.ts, models/category/package.json, models/commons/package.json, models/commons/src/localized-string/presets/of-slugs.ts, utils/package.json, utils/src/create-related-dates.ts, yarn.lock
Replace deleted fakerjs library with the new community package. 
https://github.com/faker-js/faker
=> refactor(fakerjs): use the new fakerjs community package

.github/workflows/release.yml
Address following warning message:
```
Warning: The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
```
[ref](
https://github.com/commercetools/test-data/runs/4940171642?check_suite_focus=true#step:10:8)
=> chore: update changesets/action version

.changeset/shaggy-mails-hammer.md, models/commons/src/address/address-draft/generator.ts
The latest version of `@faker-js/faker` is deprecating `address.streetSuffix()` and throwing an error during test runs
=> Address draft: fix fake  deprecated field

.changeset/fluffy-taxis-speak.md, models/category/src/builder.spec.ts, models/category/src/types.ts, models/channel/src/builder.spec.ts, models/channel/src/types.ts, models/commons/src/localized-string/helpers.ts
Our GraphQL queries return `null` when an entity doesn't have a localized value
For consistency we should also return `null` instead of `undefined`
=> Localized String: return null instead of undefined for empty values

jest.test.config.js, package.json, setup-test-framework.js, yarn.lock
This should help catching these deprecation warnings earlier.
=> chore: fail tests on console warn/error

.changeset/odd-penguins-yell.md, models/cart-discount/LICENSE, models/cart-discount/README.md, models/cart-discount/package.json, models/cart-discount/src/builder.spec.ts, models/cart-discount/src/builder.ts, models/cart-discount/src/cart-discount-draft/builder.spec.ts, models/cart-discount/src/cart-discount-draft/builder.ts, models/cart-discount/src/cart-discount-draft/generator.ts, models/cart-discount/src/cart-discount-draft/index.ts, models/cart-discount/src/cart-discount-draft/presets/index.ts, models/cart-discount/src/cart-discount-draft/transformers.ts, models/cart-discount/src/constants.ts, models/cart-discount/src/generator.ts, models/cart-discount/src/index.ts, models/cart-discount/src/presets/index.ts, models/cart-discount/src/transformers.ts, models/cart-discount/src/types.ts, yarn.lock
This PR creates the [`CartDiscount`](https://docs.commercetools.com/api/projects/cartDiscounts#cartdiscount) model.
More of the same, pretty standard migration stuff.
=> chore(test-data): create `CartDiscount` and associated draft

.changeset/four-years-listen.md, models/attribute/LICENSE, models/attribute/README.md, models/attribute/package.json, models/attribute/src/attribute-draft/builder.spec.ts, models/attribute/src/attribute-draft/builder.ts, models/attribute/src/attribute-draft/generator.ts, models/attribute/src/attribute-draft/index.ts, models/attribute/src/attribute-draft/presets/index.ts, models/attribute/src/attribute-draft/transformers.ts, models/attribute/src/builder.spec.ts, models/attribute/src/builder.ts, models/attribute/src/generator.ts, models/attribute/src/index.ts, models/attribute/src/presets/index.ts, models/attribute/src/transformers.ts, models/attribute/src/types.ts, yarn.lock
This PR creates the [Attribute](https://docs.commercetools.com/api/projects/products#attribute) model. This relates to FCT-188 as it is a dependent model for `ProductVariant`.
The patterns I used here deviate from our norm of representing REST models with the generator type, because the REST representation and graphql representation differ (graphql representation pictured below).
I chose to rename the generator type to `TModelDefault`, in line with our tests, and keep the REST type aliased to the SDK type as usual, so that the type API's for these npm modules remain consistent.
=> chore(test-data): create `Attribute` model

.changeset/tidy-pianos-shave.md, models/customer-group/src/customer-group-draft/presets/index.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/employee.spec.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/employee.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/index.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/luxe.spec.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/luxe.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/vip.spec.ts, models/customer-group/src/customer-group-draft/presets/sample-data-fashion/vip.ts, models/customer-group/src/index.ts, models/zone/src/zone-draft/presets/index.ts
- Customer group draft [presets](https://github.com/commercetools/test-data-research/blob/main/src/entity-drafts/customer-groups.ts) for fashion sample data
- Fixed zone draft preset export casing for consistency
=> feat(presets/customer-group): draft presets for fashion sample data

.changeset/quick-poets-travel.md, models/order/LICENSE, models/order/README.md, models/order/package.json, models/order/src/builder.spec.ts, models/order/src/builder.ts, models/order/src/constants.ts, models/order/src/generator.ts, models/order/src/index.ts, models/order/src/order-from-cart-draft/builder.spec.ts, models/order/src/order-from-cart-draft/builder.ts, models/order/src/order-from-cart-draft/generator.ts, models/order/src/order-from-cart-draft/index.ts, models/order/src/order-from-cart-draft/presets/index.ts, models/order/src/order-from-cart-draft/transformers.ts, models/order/src/presets/index.ts, models/order/src/transformers.ts, models/order/src/types.ts, package.json, pnpm-lock.yaml
This PR creates the above models. It also updates the order module's SDK package to include the latest, as some of the documented fields were not included in the types we were using.
=> chore(test-data): create `Order` and `OrderFromCartDraft` models

core/src/@jackfranklin/test-data-bot/index.ts, models/category/package.json, models/customer-group/package.json, models/image/package.json, models/zone/package.json, pnpm-lock.yaml
This PR was initially intended to change the imports of lodash to `lodash/utility` to provide consistency with other repos  but then I found some instances where `lodash` was added into models and never used so I removed those as well. I hope that's okay 😅
=> chore: remove unused lodash dep in some models

.changeset/nice-toys-divide.md, models/discount-code/src/discount-code-draft/presets/empty.spec.ts, models/discount-code/src/discount-code-draft/presets/empty.ts, models/discount-code/src/discount-code-draft/presets/index.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/employee-sale.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/employee-sale.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/index.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/shirts-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/shirts-bogo.ts, models/discount-code/src/discount-code-draft/transformers.ts
This PR creates presets for discount code drafts that conforms to [this data](https://github.com/commercetools/test-data-research/blob/main/src/entity-drafts/discount-codes.ts)
Been a while since being in this repo, so I'd appreciate some eagle eyes here!
=> chore(test-data): create `discountCodeDraft` presets

.changeset/kind-rabbits-buy.md, models/order/src/order-from-cart-draft/builder.ts, models/order/src/order-from-cart-draft/presets/empty.spec.ts, models/order/src/order-from-cart-draft/presets/empty.ts, models/order/src/order-from-cart-draft/presets/index.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/index.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/jamie-cart-01.spec.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/jamie-cart-01.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/john-cart-01.spec.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/john-cart-01.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/john-cart-02.spec.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/john-cart-02.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/mary-cart-01.spec.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/mary-cart-01.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/mary-cart-02.spec.ts, models/order/src/order-from-cart-draft/presets/sample-data-fashion/mary-cart-02.ts
This PR adds the [orders presets](https://github.com/commercetools/test-data-research/blob/main/src/entity-drafts/orders.ts) for Fashion Sample Data.
=> feat(test-data): add order-from-cart-draft presets

.changeset/funny-lemons-boil.md, models/tax-category/src/tax-category/tax-category-draft/presets/empty.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/empty.ts, models/tax-category/src/tax-category/tax-category-draft/presets/index.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-fashion/standard-tax-category.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-fashion/standard-tax-category.ts, models/tax-category/src/tax-rate/tax-rate-draft/presets/empty.spec.ts, models/tax-category/src/tax-rate/tax-rate-draft/presets/empty.ts, models/tax-category/src/tax-rate/tax-rate-draft/presets/index.ts
This PR fixes an incorrect import in the tax category package, which caused non-draft entities to be stubbed rather than draft entities. Additionally, I've created `empty` presets where necessary to support snapshot testing.
=> fix(test-data): fix minor incorrect import

models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-fashion/standard-tax-category.spec.ts
This PR adds a graphql build snapshot test for the Fashion Sample Data `taxCategory` preset.
=> fix(taxCategory): add graphql snapshot test

.changeset/heavy-owls-relate.md, models/line-item/src/line-item-draft/generator.ts, models/product-variant/src/product-variant/generator.ts, models/product-variant/src/product-variant/product-variant-draft/generator.ts, models/product/src/product-data/generator.ts, models/product/src/product/generator.ts, models/product/src/product/product-draft/generator.ts
refactor(sku and slug): update handling of sku to use a random word followed by 3 random alphanumeric characters to insure sku uniqueness in line-item, product-variant, product-variant-draft, product-data, and product generator.ts files.  update slug to use localizedString slug preset in product-draft generator.ts file
=> PANGOLIN-2727: Update handling of SKU's to be more random/unique, update handling of slug in product-draft

.changeset/hip-tomatoes-train.md, models/cart/src/cart-draft/presets/sample-data-fashion/john-doe-02.ts, models/cart/src/cart-draft/presets/sample-data-fashion/mary-smith-02.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/employee-sale.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/employee-sale.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/shirts-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-fashion/shirts-bogo.ts
Due to a restriction in the GraphQL CoCo API [discussed here](https://commercetools.slack.com/archives/C010MT0L58D/p1684525621747999), we must use `id` to identify cart discounts in `DiscountCodeDraft` presets.
This PR simply adds arguments to our presets and updates snapshots appropriately.
=> fix(test-data): prefer `id` resource identifiers in discount code presets

.changeset/hungry-dots-kick.md, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-fashion/europe.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-fashion/europe.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-fashion/index.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-fashion/usaAustralia.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-fashion/usaAustralia.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/change-history-data/with-usd-currency.ts
This PR renames the `ShippingMethodDraft` presets. 
Note: AFAIK these drafts are not used in other models and are only built in `mc-services` when the import takes place.
=> FCT-426 update shipping method names

.github/renovate.json
Disables the renovate `lockfileMaintenance` PR due to some inconsistencies in version numbers that we have seen recently in that PR.
See [this slack thread](https://commercetools.slack.com/archives/C04NE7LQXV3/p1691155743054109?thread_ts=1691087263.446609&cid=C04NE7LQXV3) for more context
=> fix(renovate): disable lockfileMaintenance PR in renovate config

.changeset/modern-parrots-attack.md, models/commons/src/key-reference/presets/customer-reference.spec.ts, models/commons/src/key-reference/presets/customer-reference.ts, models/commons/src/key-reference/presets/index.ts, models/payment/src/payment-method-info/payment-method-info-draft/presets/empty.spec.ts, models/payment/src/payment-method-info/payment-method-info-draft/presets/empty.ts, models/payment/src/payment-method-info/payment-method-info-draft/presets/index.ts, models/payment/src/payment-status/payment-status-draft/presets/empty.spec.ts, models/payment/src/payment-status/payment-status-draft/presets/empty.ts, models/payment/src/payment-status/payment-status-draft/presets/index.ts, models/payment/src/payment/payment-draft/presets/empty.spec.ts, models/payment/src/payment/payment-draft/presets/empty.ts, models/payment/src/payment/payment-draft/presets/index.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/index.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus1.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus1.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus2.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus2.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-usa.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-usa.ts, models/payment/src/transaction/index.ts, models/payment/src/transaction/transaction-draft/presets/empty.spec.ts, models/payment/src/transaction/transaction-draft/presets/empty.ts, models/payment/src/transaction/transaction-draft/presets/index.ts
This PR adds sample data payment presets, and empty presets for `payment-draft`, `transaction-draft`, `payment-status-draft`.
=> FCT-451: add payment presets to orders

.changeset/large-worms-peel.md, models/store/src/store/store-draft/presets/sample-data-fashion/store-01.spec.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-02.spec.ts, models/store/src/store/store-draft/presets/sample-data-fashion/store-03.spec.ts, models/store/src/store/store-draft/transformers.ts, models/store/src/store/types.ts
Local testing of the import resolver yielded errors, due to an invalid GraphQL type of the `name` field in `StoreDraft` presets. Just resolving that here 🤓 
```
{
"status": "rejected",
"reason": {
"message": "Variable '$draft' expected value of type 'CreateStore!' but got: {\"key\":\"sample_store_one\",\"name\":{\"en-US\":\"Sample Store One\"},\"__typename\":\"StoreDraft\"}. Reason: 'name[0].locale' Expected non-null value, found null.",
"extensions": { "code": "InvalidInput" }
}
},
```
=> chore(test-data): fix `StoreDraft.name` graphql type

.changeset/lovely-jars-trade.md, models/zone/src/zone/zone-draft/presets/index.ts, models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-germany.spec.ts, models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-germany.ts, models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-unitedkingdom.spec.ts, models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-unitedkingdom.ts, models/zone/src/zone/zone-draft/presets/sample-data-goodstore/index.ts
The original zone PR got a tad overwhelming with the failed test and attempted updates. Hoping this one is cleaner.
=> feat(zone): added presets for goodstore data

.changeset/shaggy-rings-suffer.md, models/store/src/store/store-draft/generator.ts, models/store/src/store/store-draft/presets/index.ts, models/store/src/store/store-draft/presets/sample-data-goodstore/index.ts, models/store/src/store/store-draft/presets/sample-data-goodstore/the-good-store.spec.ts, models/store/src/store/store-draft/presets/sample-data-goodstore/the-good-store.ts
Added store presets to the good store data. Did not include the countries as the project only supports those two countries. Info seemed redundant. 
Mirrors orginal Good Store data. https://github.com/frontastic-developers/customer-thegoodstore/blob/master/getting-started/data/stores.json
=> feat(store): added store presets for goodstore data

.changeset/light-seas-sort.md, models/product-type/README.md, models/product-type/src/attribute-boolean-type/attribute-boolean-type-draft/generator.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/builder.spec.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/builder.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/generator.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/index.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/presets/index.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/transformers.ts, models/product-type/src/attribute-localized-enum-type/builder.spec.ts, models/product-type/src/attribute-localized-enum-type/builder.ts, models/product-type/src/attribute-localized-enum-type/generator.ts, models/product-type/src/attribute-localized-enum-type/index.ts, models/product-type/src/attribute-localized-enum-type/presets/index.ts, models/product-type/src/attribute-localized-enum-type/transformers.ts, models/product-type/src/attribute-localized-enum-type/types.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/builder.spec.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/builder.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/generator.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/index.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/presets/index.ts, models/product-type/src/attribute-localized-enum-value/attribute-localized-enum-value-draft/transformers.ts, models/product-type/src/attribute-localized-enum-value/builder.spec.ts, models/product-type/src/attribute-localized-enum-value/transformers.ts, models/product-type/src/attribute-localized-enum-value/types.ts, models/product-type/src/index.ts, models/product-type/src/product-type/product-type-draft/generator.ts, models/product-type/src/product-type/product-type-draft/transformers.ts, models/product-type/src/product-type/transformers.ts, models/product-type/src/product-type/types.ts
- Added `AttributeLocalizedEnumType` and `AttributeLocalizedEnumTypeDraft` models
- Added `AttributeLocalizedEnumValueDraft` for type draft model support
- Cleaned up imports in `product-type` directory
=> feat(models/product-type): add `AttributeLocalizedEnumType`, `AttributeLocalizedEnumTypeDraft`, and `AttributeLocalizedEnumValueDraft` models

.changeset/big-garlics-cheat.md, models/product-type/README.md, models/product-type/src/attribute-enum-type/builder.spec.ts, models/product-type/src/attribute-enum-type/transformers.ts, models/product-type/src/attribute-enum-type/types.ts, models/product-type/src/attribute-localizable-text-type/builder.spec.ts, models/product-type/src/attribute-localizable-text-type/transformers.ts, models/product-type/src/attribute-localizable-text-type/types.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/builder.spec.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/builder.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/generator.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/index.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/presets/index.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/transformers.ts, models/product-type/src/attribute-set-type/builder.spec.ts, models/product-type/src/attribute-set-type/builder.ts, models/product-type/src/attribute-set-type/generator.ts, models/product-type/src/attribute-set-type/index.ts, models/product-type/src/attribute-set-type/presets/index.ts, models/product-type/src/attribute-set-type/transformers.ts, models/product-type/src/attribute-set-type/types.ts, models/product-type/src/index.ts
- Create attribute set type and draft models
- Cleaned up GraphQL type names for various other attribute types
=> feat(models/product-type): add `AttributeSetType` and `AttributeSetTpeDraft` models

.changeset/happy-comics-think.md, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/index.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/us-tax-category.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-goodstore/us-tax-category.ts
Added US to the goodstore tax presets. The two US customers are from NY and NC, therefore only the two state taxes were added.
=> feat(tax category): edit goodstore presets to include US

.changeset/great-actors-sort.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/product-discount/package.json, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.ts, pnpm-lock.yaml
This PR gets rid of shims we had previously used in goodstore data presets.
=> chore(test-data): unstub shims in goodstore data

.changeset/hip-seals-sell.md, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/express.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/standard.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.spec.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-10000.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-50000.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-10000.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-50000.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/usd-5000.spec.ts, models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/usd-5000.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe-express.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/united-kingdom.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/usa.spec.ts
This is a fix identified from an ongoing integration effort
=> fix(test-data): use Money over CentPrecisionMoney in shipping rate drafts

.changeset/spotty-maps-hug.md, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/builder.spec.ts, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/builder.ts, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/generator.ts, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/index.ts, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/presets/index.ts, models/product-type/src/attribute-localizable-text-type/attribute-localized-text-type-draft/transformers.ts, models/product-type/src/attribute-localizable-text-type/types.ts, models/product-type/src/index.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.ts
All attribute types had a draft model, except this one. Created it for symmetry and transformed it accordingly to meet the graphql schema's needs.
=> chore(test-data): create `AttributeLocalizableTextTypeDraft` model

.changeset/nasty-trees-talk.md, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/bedding-bundle-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/bedding-bundle-01.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/classic-champagne-glasses-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/classic-champagne-glasses-01.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/cotton-silk-bedsheet-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-goodstore/cotton-silk-bedsheet-01.ts, models/product/src/product/product-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts, models/product/src/product/product-draft/presets/sample-data-goodstore/classic-champagne-glasses.spec.ts, models/product/src/product/product-draft/presets/sample-data-goodstore/cotton-silk-bedsheet.spec.ts
This PR fixes three product presets for goodstore data that were not importing correctly.
=> chore(test-data): fix product presets with correct datatypes

.changeset/brave-turtles-swim.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts
We encountered issues regarding cart recalculation latency when converting carts into orders, and have chosen to deactivate cart discounts and discount codes to mitigate this issue.
=> chore(test-data): deactivate discounts for goodstore

.changeset/slimy-mangos-give.md, models/payment/package.json, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus1.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus1.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus2.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-aus2.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-usa.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-fashion/payment-usa.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/jennifer-jones-payment.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/jennifer-jones-payment.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/sebastian-mueller-payment.spec.ts, models/payment/src/payment/payment-draft/presets/sample-data-goodstore/sebastian-mueller-payment.ts, pnpm-lock.yaml
This PR adds keys to `PaymentDraft` presets for both Fashion and GoodStore sample data - this will simplify the process of assigning payments to orders in the import resolver.
=> fix(presets): add keys to payment presets

.changeset/tiny-dragons-care.md, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts, models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-bakeware.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-furniture-and-decor.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.spec.ts, models/product-discount/src/product-discount/product-discount-draft/presets/sample-data-goodstore/discount-new-arrivals.ts
Flip flopping into deactivated discounts to ensure we can create our data error-free.
=> chore(test-data): deactivate goodstore discount presets

.changeset/kind-hairs-suffer.md, .env.template, codegen.settings.yml, graphql-types/LICENSE, graphql-types/README.md, graphql-types/package.json, graphql-types/src/generated/.gitattributes, graphql-types/src/generated/settings.ts, graphql-types/src/index.ts, jest.eslint.config.js, models/custom-view/package.json, models/custom-view/src/custom-view-permission/generator.ts, models/custom-view/src/custom-view-permission/types.ts, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, schemas/settings.json
Initial refactoring to leverage generated graphql types to define graphql models
=> feat: use generated graphql types

.changeset/eleven-turkeys-cry.md, models/custom-view/src/custom-view/custom-view-draft/builder.spec.ts, models/custom-view/src/custom-view/custom-view-draft/generator.ts, models/custom-view/src/custom-view/types.ts
We don't need to have status in the customViewDraft. 
See the [CustomViewDraftDataInput](https://github.com/commercetools/merchant-center-services/blob/0edc1501facd3a24501dfacae65aed7197671168/packages/settings/lib/schemas/custom-view.graphql#L135) in the schema
=> Remove status from custom view draft

.changeset/rude-colts-brush.md, models/quote-request/src/builder.spec.ts, models/quote-request/src/generator.ts, models/quote-request/src/quote-request-draft/generator.ts, models/quote-request/src/transformers.ts, models/quote-request/src/types.ts, models/staged-quote/LICENSE, models/staged-quote/README.md, models/staged-quote/package.json, models/staged-quote/src/builder.spec.ts, models/staged-quote/src/builder.ts, models/staged-quote/src/constants.ts, models/staged-quote/src/generator.ts, models/staged-quote/src/index.ts, models/staged-quote/src/presets/index.ts, models/staged-quote/src/staged-quote-draft/builder.spec.ts, models/staged-quote/src/staged-quote-draft/builder.ts, models/staged-quote/src/staged-quote-draft/generator.ts, models/staged-quote/src/staged-quote-draft/index.ts, models/staged-quote/src/staged-quote-draft/presets/index.ts, models/staged-quote/src/staged-quote-draft/transformers.ts, models/staged-quote/src/transformers.ts, models/staged-quote/src/types.ts, pnpm-lock.yaml
This PR adds a new package for the `StagedQuote` and `StagedQuoteDraft` [models](https://docs.commercetools.com/api/projects/staged-quotes).
=> Pangolin 3184: staged quote model

.changeset/plenty-jobs-brush.md, models/quote-request/src/transformers.ts, models/quote-request/src/types.ts, models/quote/LICENSE, models/quote/README.md, models/quote/package.json, models/quote/src/builder.spec.ts, models/quote/src/builder.ts, models/quote/src/constants.ts, models/quote/src/generator.ts, models/quote/src/index.ts, models/quote/src/presets/index.ts, models/quote/src/quote-draft/builder.spec.ts, models/quote/src/quote-draft/builder.ts, models/quote/src/quote-draft/generator.ts, models/quote/src/quote-draft/index.ts, models/quote/src/quote-draft/presets/index.ts, models/quote/src/quote-draft/transformers.ts, models/quote/src/transformers.ts, models/quote/src/types.ts, models/staged-quote/src/transformers.ts, models/staged-quote/src/types.ts, pnpm-lock.yaml
This PR adds a new package for the `Quote` and `QuoteDraft` [models](https://docs.commercetools.com/api/projects/quotes).
=> Pangolin 3186: add `quote` model

.changeset/five-shirts-shout.md, models/business-unit/src/company/transformers.ts, models/business-unit/src/division/transformers.ts, pnpm-lock.yaml
This adds the typename fields to the transformers of Division and Company. Thus enabling us to use it in our graphql based tests.
=> chore(business-unit): add typename fields to graphql transformers

.changeset/popular-falcons-share.md, models/business-unit/src/company/builder.spec.ts, models/business-unit/src/company/builder.ts, models/business-unit/src/company/company-draft/builder.spec.ts, models/business-unit/src/company/company-draft/builder.ts, models/business-unit/src/company/company-draft/generator.ts, models/business-unit/src/company/company-draft/transformers.ts, models/business-unit/src/company/generator.ts, models/business-unit/src/company/transformers.ts, models/business-unit/src/division/builder.spec.ts, models/business-unit/src/division/builder.ts, models/business-unit/src/division/division-draft/builder.spec.ts, models/business-unit/src/division/division-draft/builder.ts, models/business-unit/src/division/division-draft/generator.ts, models/business-unit/src/division/division-draft/transformers.ts, models/business-unit/src/division/generator.ts, models/business-unit/src/division/transformers.ts, models/business-unit/src/types.ts
This PR aims to replace the current scaffolding in the Company and Division models with the real implementation.
- Adds parentUnit field as null value in Company to prevent associated errors because of missing field
- Adds parentUnit and topLevelUnit to buildFields where applicable
- Adds ancestors and inheritedStores fields to graphQL transformer sprevent associated errors because of missing fields
- Replaces topLevelUnit field with itself for Company in graphQL transformer to match referenceExpansion
- Replaces parentUnit and topLevelUnit with Companies in Division graphQL transformer to match referenceExpansion
=> chore(business-unit): graphql transformers for Company and Division models

.changeset/pretty-candles-greet.md, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/express.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/express.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/standard.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/standard.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.ts
This PR adds `localizedName` values for `en-US`, `en-GB`, and `de-DE` to the good store `ShippingMethodDraft` presets, based on the existing `name` field.
=> fix(shippingMethod/presets): include localized name in good store presets

.github/CODEOWNERS
The Pangolin team isn't responsible for shared tooling and can't reliably devote time to this. However, if the goal is to properly assign ownership to the right team when changes are made, it seems like that should be directed by tech leadership with more granular code ownership assignments. Ideally, any time a new model is added or an existing, unowned model is updated, `CODEOWNERS` should be updated to reflect the correct team at that time, and we can't really make that call.
=> chore: remove pangolin from models catch-all ownership

.changeset/orange-chicken-protect.md, models/payment/src/payment-method-info/payment-method-info-draft/transformers.ts, models/payment/src/payment/payment-draft/builder.spec.ts, models/payment/src/payment/payment-draft/generator.ts, models/payment/src/transaction/transaction-draft/generator.ts
While making changes related to this [effort](https://commercetools.atlassian.net/browse/FCT-710), I found that `PaymentDraft` was not being generated correctly
=> chore(test-data): correct PaymentDraft model generation

.changeset/silent-days-fail.md, models/standalone-price/src/standalone-price-draft/builder.spec.ts, models/standalone-price/src/standalone-price-draft/generator.ts, models/standalone-price/src/standalone-price-draft/transformers.ts, models/standalone-price/src/types.ts
The standalone price draft model (`CreateStandalonePrice` in GraphQL land) has a particular shape for its `value` input:
Just making that fix here, and using `MoneyDraft` rather than `CentPrecisionMoneyDraft`.
=> chore(test-data): Fix `StandalonePriceDraft` GraphQL shape

.changeset/slimy-rocks-refuse.md, models/order/README.md, models/order/src/order-from-quote-draft/builder.spec.ts, models/order/src/order-from-quote-draft/builder.ts, models/order/src/order-from-quote-draft/generator.ts, models/order/src/order-from-quote-draft/index.ts, models/order/src/order-from-quote-draft/presets/empty.spec.ts, models/order/src/order-from-quote-draft/presets/empty.ts, models/order/src/order-from-quote-draft/presets/index.ts, models/order/src/order-from-quote-draft/transformers.ts, models/order/src/types.ts
Adds the `OrderFromQuoteDraft` [model](https://docs.commercetools.com/api/projects/orders#orderfromquotedraft) to the Orders package.
=> feat(order): add orderFromQuoteDraft model

.changeset/light-moons-divide.md, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/builder.spec.ts, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/builder.ts, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/generator.ts, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/index.ts, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/presets/index.ts, models/product-type/src/attribute-plain-enum-value/attribute-plain-enum-value-draft/transformers.ts, models/product-type/src/attribute-plain-enum-value/types.ts
Adds `attribute-plain-enum-value-draft`.
=> feat(attribute-plain-enum-value): add attribute-plain-enum-value-draft

.changeset/spotty-socks-fetch.md, models/product-selection/src/types.ts
update `TProductSelectionDraftGraphql` to use `TLocalizedStringGraphql` as type for `name` field
=> fix(product selection draft type)

.changeset/honest-bikes-think.md, models/commons/src/key-reference/key-reference-draft/presets/index.ts, models/commons/src/key-reference/key-reference-draft/presets/product-selection-reference.spec.ts, models/commons/src/key-reference/key-reference-draft/presets/product-selection-reference.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/index.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/sample-data-b2b/default-product-selection.spec.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/sample-data-b2b/default-product-selection.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/sample-data-b2b/index.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/sample-data-b2b/us-medium-customers-catalog-product-selection.spec.ts, models/store/src/product-selection-setting/product-selection-setting-draft/presets/sample-data-b2b/us-medium-customers-catalog-product-selection.ts, models/store/src/store/store-draft/presets/sample-data-b2b/de-fr-uk.spec.ts, models/store/src/store/store-draft/presets/sample-data-b2b/de-fr-uk.ts, models/store/src/store/store-draft/presets/sample-data-b2b/default-store.spec.ts, models/store/src/store/store-draft/presets/sample-data-b2b/default-store.ts, models/store/src/store/store-draft/presets/sample-data-b2b/spain.spec.ts, models/store/src/store/store-draft/presets/sample-data-b2b/spain.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-large-customers.spec.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-large-customers.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-medium-customers.spec.ts, models/store/src/store/store-draft/presets/sample-data-b2b/us-medium-customers.ts
- generates `productSelectionSettingsDraft` presets for both b2b product-selections
- references appropriate `PSSD`'s in b2b `storeDraft` presets
- creates `productSelection` keyReference preset
- adds and updates appropriate tests
=> FCT-783: Add Product Selections to Stores

.changeset/yellow-mirrors-heal.md, models/commons/src/high-precision-money/builder.spec.ts, models/commons/src/high-precision-money/builder.ts, models/commons/src/high-precision-money/generator.ts, models/commons/src/high-precision-money/high-precision-money-draft/builder.spec.ts, models/commons/src/high-precision-money/high-precision-money-draft/builder.ts, models/commons/src/high-precision-money/high-precision-money-draft/generator.ts, models/commons/src/high-precision-money/high-precision-money-draft/index.ts, models/commons/src/high-precision-money/high-precision-money-draft/presets/index.ts, models/commons/src/high-precision-money/high-precision-money-draft/transformers.ts, models/commons/src/high-precision-money/index.ts, models/commons/src/high-precision-money/presets/index.ts, models/commons/src/high-precision-money/transformers.ts, models/commons/src/high-precision-money/types.ts
In Priceless, we want to test Standalone Prices with high precision values. With that goal, and assuming that high precision money could be used elsewhere, this PR introduces `HighPrecisionMoney` and `HighPrecisionMoneyDraft` models to `@commercetools-test-data/commons`.
=> PRC-3436: Add `HighPrecisionMoney` and `HighPrecisionMoneyDraft` models

.changeset/empty-dragons-lie.md, models/discount-code/src/discount-code-draft/generator.ts
The `code` property on `discount-code-draft` is causing flaky tests. This PR adds randomness to the `code` property with an alphanumeric value so we can lessen the chance of duplicate value errors.
Example: 
```
Error in function getDiscountCodeCreateData --- Error: 
BadRequest: A duplicate value '"addo"' exists for field 'code'.
```
Reference: https://app.circleci.com/pipelines/github/commercetools/audit-log/26918/workflows/caacfa3c-1f72-4ffd-82e7-3b3b839560fc/jobs/272586/tests
=> PANGOLIN-3789: updated `code` property on discount-code-draft to fix duplicate value

.changeset/tough-crews-search.md, models/commons/README.md, models/commons/src/high-precision-money/builder.spec.ts, models/commons/src/index.ts
This PR is a follow-up/fix of https://github.com/commercetools/test-data/pull/552
`HighPrecisionMoney` related models and types were not exported 😅
=> fix: export `HighPrecisionMoney` and `HighPrecisionMoneyDraft` models and its types

.gitignore, package.json
The `link-workspace-package=true` doesn't seem to work. Let's try to isolate the issue on the pnpm version.
=> Downgrades pnpm to v8 after v9 seems to cause publishing issues

.changeset/poor-clouds-accept.md
this is the bump after the canary realize https://github.com/commercetools/test-data/pull/567
=> chore: publish last version of cart-discount package

.changeset/metal-experts-reflect.md, models/cart-discount/src/cart-discount/generator.ts
when we return the values from the card cart discount we need a complete price value not a draft, that does not mach with what the api return https://docs.commercetools.com/api/projects/cartDiscounts#cartdiscountvalue draft miss the type property.(draft are not a preset they are a different type)
we are the only team using the card discount which is the reason for omitting the canary realize.
=> chore: return required value type model from cart discount

models/cart-discount/src/cart-discount-value-gift-line-item/builder.spec.ts, models/cart-discount/src/cart-discount-value-gift-line-item/generator.ts, models/cart-discount/src/cart-discount-value-gift-line-item/transformers.ts, models/cart-discount/src/cart-discount-value-gift-line-item/types.ts
This pr Changes and now we add the missing references to the references
this pr will solve the issue the card discount value when giftline item is selected, I will go with a canary Realize becuase we are modify some hard code data on data examples
```      
Missing field 'distributionChannelRef' while writing result {
"type": "giftLineItem",
"product": {
"id": "07dff654-196d-4ba0-aae6-3508dfaf7d80",
"typeId": "product",
"__typename": "Reference"
},
"variantId": 341916377939968,
"supplyChannel": {
"id": "ba4652d3-5aef-448c-903c-c8abe4bb48cf",
"typeId": "channel",
"__typename": "Reference"
},
"distributionChannel": {
"id": "bd072d11-791a-4d67-a34a-40786c72b9df",
"typeId": "channel",
"__typename": "Reference"
},
"__typename": "GiftLineItemValue"
}```
this bug what found during …
=> chore: rename ref in graphql

.changeset/brave-lizards-doubt.md, models/cart-discount/src/cart-discount-value-gift-line-item/builder.spec.ts, models/cart-discount/src/cart-discount-value-gift-line-item/transformers.ts, models/cart-discount/src/cart-discount-value-gift-line-item/types.ts
missing field productRef. was also needed for the GraphQl response.
the bump is needed but it will not be deployed till we merge this prhttps://github.com/commercetools/test-data/pull/583
we merge to main and we get our canary.
=> add missing productRef field grapql

.changeset/tough-terms-mix.md, .github/CODEOWNERS, models/discounts-custom-view/src/builder.spec.ts, models/discounts-custom-view/src/discounts-custom-view-input/builder.spec.ts, models/discounts-custom-view/src/discounts-custom-view-input/generator.ts, models/discounts-custom-view/src/generator.ts
Generated `DiscountsCustomView.filters` and `DiscountsCustomViewInput.filter` must be an array.
Added `/models/discounts-custom-view` to `CODEOWNERS` file.
=> fix: `DiscountsCustomView.filters` and `DiscountsCustomViewInput.filter` generated data

.changeset/honest-toys-run.md, .changeset/tough-terms-mix.md, models/type/src/field-definition/builder.spec.ts, models/type/src/field-definition/transformers.ts
Add missing `labelAllLocales` property to `FieldDefinition` model (GraphQL variant)
=> fix: build `labelAllLocales` property for GraphQL `FieldDefinition` model

.changeset/many-ads-drive.md, models/product-discount/src/product-discount-value-absolute/builder.spec.ts, models/product-discount/src/product-discount-value-absolute/transformers.ts, models/product-discount/src/product-discount-value-absolute/types.ts, models/product-discount/src/product-discount-value-external/builder.spec.ts, models/product-discount/src/product-discount-value-external/transformers.ts, models/product-discount/src/product-discount-value-external/types.ts, models/product-discount/src/product-discount-value-relative/builder.spec.ts, models/product-discount/src/product-discount-value-relative/transformers.ts, models/product-discount/src/product-discount-value-relative/types.ts
Due to wrong typenames, Apollo Client is not caching the queries in tests.
=> fix: `ProductDiscountValueAbsolute`, `ProductDiscountValueExternal`, and `ProductDiscountValueRelative` `__typename` fields

.changeset/twelve-bikes-yell.md, models/product-type/src/attribute-plain-enum-value/builder.spec.ts, models/product-type/src/attribute-plain-enum-value/transformers.ts, models/product-type/src/attribute-plain-enum-value/types.ts
`AttributePlainEnumValue` is building a wrong `__typename` prop.
=> fix: `AttributePlainEnumValue` GraphQL `__typename` field

.changeset/spotty-kids-cover.md, models/type/src/custom-field-enum-type/builder.spec.ts, models/type/src/custom-field-enum-type/transformers.ts, models/type/src/custom-field-enum-type/types.ts, models/type/src/custom-field-enum-value/builder.spec.ts, models/type/src/custom-field-enum-value/generator.ts, models/type/src/custom-field-enum-value/transformers.ts, models/type/src/custom-field-enum-value/types.ts, models/type/src/custom-field-localized-enum-type/builder.spec.ts, models/type/src/custom-field-localized-enum-value/builder.spec.ts, models/type/src/custom-field-localized-enum-value/transformers.ts, models/type/src/custom-field-localized-enum-value/types.ts
Changes in this PR:
- CustomFieldEnumType:
- `__typename` changed: from `EnumCustomFieldType` to `EnumType`.
- CustomFieldEnumValue
- `label` field is a string.
- `labelAllLocales` field removed and `label` field added to GraphQL model.
- `__typename` changed: from `LocalizableEnumValueType` to `EnumValue`.
- CustomFieldLocalizedEnumValue
- `__typename` changed: from `LocalizableEnumValueType` to `LocalizedEnumValue`.
=> fix: wrong `__typenames` props (CustomFieldEnumType, CustomFieldEnumValue, CustomFieldLocalizedEnumValue)

.changeset/hot-tips-serve.md, models/product-discount/src/product-discount-value-absolute/builder.spec.ts, models/product-discount/src/product-discount-value-absolute/generator.ts
ProductDiscountValueAbsolute  money  must return an array of the type [CentPrecisionMoney](https://docs.commercetools.com/api/types#ctp:api:type:CentPrecisionMoney)
https://docs.commercetools.com/api/projects/productDiscounts#productdiscountvalueabsolute
this fix also fixes the flakiness when using the ProductDiscount.random() test model.
=> Ma fix wrong money value on product discount

models/product-type/src/attribute-enum-type/builder.spec.ts, models/product-type/src/attribute-enum-type/transformers.ts, models/product-type/src/attribute-enum-type/types.ts
- Wraps PlainEnumValue type with results, as done on `attribute-localized-enum-type` as seen below:
https://github.com/commercetools/test-data/blob/827861fe7d04e297cfed09efd4646659f8e260d1/models/product-type/src/attribute-localized-enum-type/transformers.ts#L22-L31
- Tested the updated `@commercetools-test-data/product-type` package locally against all products and discounts tests where it is being used.
=> fix(attribute-enum-type): add missing results wrapper

.changeset/clever-taxis-carry.md, .changeset/curvy-cycles-switch.md, .changeset/yellow-rats-wait.md, models/category/package.json, models/category/src/builder.spec.ts, models/category/src/transformers.ts, models/category/src/types.ts, models/commons/src/localized-string/helpers.ts, models/commons/src/localized-string/index.ts, models/product/src/product-data/builder.spec.ts, models/product/src/product-data/transformers.ts, models/product/src/product-data/types.ts, pnpm-lock.yaml
There are some properties in the test data models that are locale based but we're not handling them in a way that resembles the way they are handled in the GraphQL context.
Let's take the Category model `name` property as an example.
In the Core definition for that model, the `name` property is a `LocalizedString` type, which is an object that contains a map of locale to string, so that's what we configure [in the model's generator](https://github.com/commercetools/test-data/blob/main/models/category/src/generator.ts#L20).
However, the GraphQL representation of that property is defined as an array of [TLocalizedStringGraphql](https://github.com/commercetools/test-data/blob/main/models/commons/src/localized-string/types.ts#L6) type, which is an object that contains the locale and the …
=> Update management of locale-based props for GraphQL transformers

.github/CODEOWNERS, models/product-projection/LICENSE, models/product-projection/README.md, models/product-projection/package.json, models/product-projection/src/builder.spec.ts, models/product-projection/src/builder.ts, models/product-projection/src/generator.ts, models/product-projection/src/index.ts, models/product-projection/src/presets/happy-cow-milk-product-projection.ts, models/product-projection/src/presets/index.ts, models/product-projection/src/transformers.ts, models/product-projection/src/types.ts, pnpm-lock.yaml
As part of the effort to [remove the local test data models](https://commercetools.atlassian.net/browse/FEC-26) we have in the Merchant Center monorepo, we noticed the `ProductProjection` model did not exist yet in this repository, so this PR introduces it.
[Here](https://docs.commercetools.com/api/projects/productProjections) is the public technical documentation about this model.
=> New `ProductProjection` model

.changeset/silent-colts-hunt.md, .changeset/stupid-dolls-peel.md, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-sets.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-sets.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed-01.spec.ts, models/product/src/product-variant/product-variant-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed-01.ts, models/product/src/product/product-draft/presets/sample-data-b2c-lifestyle/serenity-queen-bed.spec.ts
This pull request includes several changes aimed at fixing and updating attributes for the B2C sample data import. The most important changes include adding a new attribute to the product type and correcting the declaration of an existing attribute in the product draft.
* Added a new `finish` attribute to the `product-sets` product type in multiple locales (`en-GB`, `en-US`, `de-DE`). (`models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-sets.spec.ts`: [[1]](diffhunk://#diff-ae3a29babb97604b9d6fd97d9243bc43ecdbdb57dc506d3d9db5197d7eb4a1d6R53-R71) [[2]](diffhunk://#diff-ae3a29babb97604b9d6fd97d9243bc43ecdbdb57dc506d3d9db5197d7eb4a1d6R144-R170); `models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/product-set …
=> FCT-fix update b2c test data to match types for specific products and product-variants

jest.eslint.config.js
This PR fixes an issue where staged linting would fail when committing **only** spec files containing the word `build` in their name (e.g., builder.spec.ts).
Curiously, the commit would succeed if any other file was staged alongside the spec file.
The linter misinterpreted `build` as part of the main `build` directory path.
This issue was resolved by adding slashes around `build` in `modulePathIgnorePatterns` to target the `build` directory more specifically.
For more details
https://commercetools.slack.com/archives/GCSJ9T12P/p1724329299796769
=> Fix stage-linting issue when committing spec files containing ‘build’ in their path or file name

models/customers-search-list-my-view/LICENSE, models/customers-search-list-my-view/README.md, models/customers-search-list-my-view/package.json, models/customers-search-list-my-view/src/builder.spec.ts, models/customers-search-list-my-view/src/builder.ts, models/customers-search-list-my-view/src/generator.ts, models/customers-search-list-my-view/src/index.ts, models/customers-search-list-my-view/src/presets/index.ts, models/customers-search-list-my-view/src/transformers.ts, models/customers-search-list-my-view/src/types.ts, pnpm-lock.yaml
A new model `CustomersSearchListMyView` is created based on the existing test-data in the FE repository. This model is related to internal [MC-settings graphql](https://github.com/commercetools/merchant-center-services/blob/main/packages/settings/lib/schemas/customers-search-list-my-view.graphql)
=> FEC-56: Add `CustomersSearchListMyView` my view model

.changeset/sweet-walls-whisper.md, models/customers-search-list-my-view/package.json, pnpm-lock.yaml
In the previous PR, I kept the version as `1.0.0` which is fixed in this PR. I also created changeset for the release
=> FEC-56: update model version

.changeset/ten-ants-act.md, .github/CODEOWNERS, models/attribute-group/LICENSE, models/attribute-group/README.md, models/attribute-group/package.json, models/attribute-group/src/builder.spec.ts, models/attribute-group/src/builder.ts, models/attribute-group/src/generator.ts, models/attribute-group/src/index.ts, models/attribute-group/src/presets/index.ts, models/attribute-group/src/transformers.ts, models/attribute-group/src/types.ts, pnpm-lock.yaml
A new model `attribute-group` is created based on the existing test-data in the FE repository. 
Note: The parent PR is in draft mode due to the `inventory-entry` update being done in a separate PR. This PR can be reviewed independently. I will merge this PR only after parent PR is unblocked and reviewed.
=> FEC-39: Create `Attribute-group` model

.changeset/hip-hairs-compare.md, models/product/src/image/builder.spec.ts, models/product/src/image/transformers.ts, models/product/src/image/types.ts, models/product/src/product-variant/builder.spec.ts
This PR fixes `image` model image dimension graphQL keys needed for this [migration PR](https://github.com/commercetools/merchant-center-frontend/pull/17434) which is based on [batch 12](https://commercetools.atlassian.net/browse/FEC-49) of the [chapter epic](https://commercetools.atlassian.net/browse/FEC-26) where we are migrating tests to use public test-data package
=> [FEC-49] -fix dimension keys inside graphql representation

README.md
Thanks to @dogayuksel and @antoniolodias for sharing the local development steps during the chapter rotation work. It made the development process easier, rather than copy/pasting dist folder inside node_modules. This PR adds the local development steps to the README.md file.
=> docs: Add local development steps

.changeset/rude-games-sin.md, models/category/src/category-search/builder.spec.ts, models/category/src/category-search/builder.ts, models/category/src/category-search/generator.ts, models/category/src/category-search/index.ts, models/category/src/category-search/presets/index.ts, models/category/src/category-search/presets/with-parent-and-ancestors.spec.ts, models/category/src/category-search/presets/with-parent-and-ancestors.ts, models/category/src/category-search/presets/with-parent.spec.ts, models/category/src/category-search/presets/with-parent.ts, models/category/src/category-search/transformers.ts, models/category/src/index.ts, models/category/src/types.ts, models/state/src/builder.spec.ts, models/state/src/transformers.ts, models/state/src/types.ts
The `name` field in state model is transformed for graphql. A new `CategorySearch` model is added under category.
Note: `CategorySearch` is a deprecated graphql service and it is used only in category search page which was developed long time ago.
=> FEC-60: Fix `state` model and add `CategorySearch` model

.changeset/witty-apes-trade.md, models/product-type/package.json, models/product-type/src/index.ts, models/product-type/src/type-definition/builder.spec.ts, models/product-type/src/type-definition/builder.ts, models/product-type/src/type-definition/generator.ts, models/product-type/src/type-definition/index.ts, models/product-type/src/type-definition/transformers.ts, models/product-type/src/type-definition/types.ts, models/type/src/index.ts, pnpm-lock.yaml
This PR creates `type definition` model needed for this [migration PR](https://github.com/commercetools/merchant-center-frontend/pull/17434) which is based on [batch 12](https://commercetools.atlassian.net/browse/FEC-49) of the [chapter epic](https://commercetools.atlassian.net/browse/FEC-26) where we are migrating tests to use public test-data package
=> [FEC-49] - add type definition model

.changeset/dry-peas-return.md, models/state/src/transformers.ts, models/state/src/types.ts
The `name` field should be `null` if the nameAllLocales is undefined. The jest throws error when the name is undefined.
=> FEC-60: Adjust `state` model to send `null` as fallback

models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-b2b/standard-tax.spec.ts, models/tax-category/src/tax-category/tax-category-draft/presets/sample-data-b2b/standard-tax.ts
## [B2B sample data]: set us standard vat not included in price
Small PR to update the standard VAT since all other US tax categories don't include the tax in the price. This change ensures consistency across the tax categories on the US and was requested by commercetools FE.
=> [B2B sample data]: set us standard vat not included in price

.changeset/great-pandas-run.md, models/standalone-price/src/builder.spec.ts, models/standalone-price/src/generator.ts, models/standalone-price/src/staged-standalone-price/transformers.ts, models/standalone-price/src/transformers.ts, models/standalone-price/src/types.ts
This PR updates the Standalone price model to improve consistency in our unit tests and provide a more realistic model that aligns with our GraphQL schema and form limitations.
Currencies are synced now with the main value currency code.
=> Update Standalone price model

.changeset/many-ducks-study.md, models/cart-discount/src/cart-discount-value-absolute/builder.spec.ts, models/cart-discount/src/cart-discount-value-absolute/constants.ts, models/cart-discount/src/cart-discount-value-absolute/transformers.ts, models/cart-discount/src/cart-discount-value-absolute/types.ts
To properly test Cart Discount Application Modes feature, the new field needs to be added to the `CartDiscountValueAbsolute` model.
=> feat: add applicationMode field to `CartDiscountValueAbsolute` model

.changeset/funny-ties-jog.md, models/commons/src/cent-precision-money/cent-precision-money-draft/generator.ts, models/commons/src/cent-precision-money/generator.ts
This PR adds a max value for the `centAmount` field in the `CentPrecisionMoney` and `CentPrecisionMoneyDraft` models. The reason is rounding errors can occur when the `centAmount` value is too large, so we want to limit the value to a reasonable range.
Uploading Screen Recording 2024-09-24 at 16.40.35.mov…
=> fix(CentPrecisionMoney): add max centAmount value to CentPrecisionMoney and CentPrecisioMoneyDraft

CONTRIBUTING.md, docs/contributing/test-data-models-overview.md, docs/guidelines/creating-new-model.md, docs/test-data-models-overview.md
This PRs add new documentation to the repository where we explain how new test data models look like and how to build them.
=> New test data models documentation

.changeset/brown-spiders-impress.md, core/src/helpers.ts
**Description**
This PR upgrades type accuracy for list builder helpers by introducing a second type parameter for the transformed output model (either GraphQL or REST).
- Previously, only the base model type was specified, representing the model from which the GraphQL or REST representations were derived. As a result, the returned data type did not accurately reflect the transformed output of these representations.
- Now, by specifying both the base model type and the transformed output type, the returned data type precisely matches the actual structure of the GraphQL and REST responses.
- For backward compatibility, the second type parameter will default to the base model (`Model`) if not provided.
- Users should now explicitly provide the `GraphqlModel` when needed:
```typescript
const …
```
=> Update core helpers to support accurate typing for transformed models

.changeset/healthy-carrots-share.md, .changeset/strange-months-hang.md, core/src/helpers.ts, core/src/transformer.ts, core/src/types.ts, models/commons/src/client-logging/transformers.ts, models/commons/src/reference/transformers.ts, models/product-type/src/attribute-enum-type/transformers.ts, models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/transformers.ts, models/product-type/src/attribute-set-type/attribute-set-type-draft/transformers.ts, models/product-type/src/product-type/product-type-draft/transformers.ts
When creating Transformers, you can provide a `buildFields` property with the list of names of the nested models fields that should be transformed.
In our latest version, we updated that behaviour so that, if you don't provide that property, the Transformer will automatically detect the nested models and build them.
There were a few models where transformers where not providing the `buildFields` properties but they meant they didn't want any nested model to be build.
In order to cover this use case, we modified the `buildFields` property to also accept `false` as a value, which was used as a signal to not build nested models and we updated those few models accordingly.
However, we discovered one of our internal packages which relies on this one had many more models with the same use case …
=> Refactor transformers behaviour for building nested models

.changeset/tidy-ravens-sort.md, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/furniture-and-decor.spec.ts, models/product-type/src/product-type/product-type-draft/presets/sample-data-b2c-lifestyle/furniture-and-decor.ts
See title. Based on [this request](https://commercetools.slack.com/archives/C03B6NKTA83/p1730211019423229).
=> fix(product-types/b2c-lifestyle): furniture and decor color attribute is now searchable

.changeset/tasty-hats-joke.md, models/commons/src/localized-string/helpers.spec.ts, models/commons/src/localized-string/helpers.ts
The `resolveGraphqlDefaultLocaleValue` helper of the `LocalizedString` model breaks when it receives an empty array as a parameter.
=> Fix LocalizedString common model helper

.changeset/giant-pans-fly.md, models/channel/src/index.ts, models/channel/src/presets/index.ts
We had a missconfiguration in the compatibility test data model for `Channel`s.
We were exporting the GraphQL presets instead of the REST ones, which made it impossible to generate REST data models out of them.
=> Fix Channel data model compat mode presets

.changeset/tough-scissors-cheat.md, models/channel/src/channel-draft/presets/index.ts
We were exporting the GraphQL presets from the legacy `ChannelDraft` model when we must use the compatibility ones.
=> Fix legacy ChannelDraft model presets

docs/guidelines/creating-new-model.md, docs/guidelines/migrating-existing-model.md
This is a follow-up of #722 where we set up GraphQL types generation so we don't need to define them in each test data model.
We're updating the docs to reflect those changes in this PR.
Also, we gathered some initial feedback around creating new models and the concept of referenced models does not seem to be very clear so I added a new section trying to explain a bit what they are and how we handle them.
=> Update data models guidelines

.changeset/strong-toys-marry.md, codegen.ctp.yml, graphql-types/src/generated/ctp.ts
This PR edits the codegen config file to prefer more specific types rather than `unknown` for scalar values. 
This work was prompted by a lack of backwards compatibility from the new changes to test-data fixtures with respect to the B2B sample import, in which `unknown` values could not be assigned to more narrow preset-defined types like `string`.
Since scalar types are now inferred more narrowly, the test-data fixture types and those same types introspected in mc-services should be identical and compatible.
Merging this in and cutting a new version will allow us to make more streamlined changes in mc-services to update the B2B feature.
=> chore(test-data): narrowly introspect scalar types

.changeset/spotty-onions-grab.md, models/inventory-entry/src/index.ts
Fixes `InventoryEntry` exports to make them symmetrical with `Channel`
=> chore(test-data): fix InventoryEntry export formatting

models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-b2b/premium-shipping-method.spec.ts, models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-b2b/standard-shipping-method.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-b2b/europe-premium.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-b2b/europe-premium.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-b2b/europe-standard.spec.ts, models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-b2b/europe-standard.ts
Fixing values after the latest change [PR#729](https://github.com/commercetools/test-data/pull/729/files):
- Standard should have value `100,00` and be free above `10.000,00`
- Premium should have value `300,00` and be free above `15.000,00`
=> Fix values for premium and standard

.changeset/healthy-seahorses-sing.md
Missing changeset for [PR#740](https://github.com/commercetools/test-data/pull/740)
Changes the values for shipping rates:
- Standard should have value 100,00 and be free above 10.000,00
- Premium should have value 300,00 and be free above 15.000,00
=> feat(changeset): adding missing changeset for shipping methods changes

.changeset/kind-games-melt.md, models/commons/src/high-precision-money/types.ts, models/commons/src/money/builder.spec.ts, models/commons/src/money/transformers.ts, models/commons/src/money/types.ts, models/commons/src/price/price-draft/transformers.ts, models/commons/src/price/types.ts, models/standalone-price/package.json, models/standalone-price/src/standalone-price-draft/transformers.ts, models/standalone-price/src/transformers.ts, models/standalone-price/src/types.ts, pnpm-lock.yaml
Money and HighPrecisionMoney now use the generated types to avoid issues downstream.
=> fix(commons): Money and HighPrecisionMoney GraphQL models types

.changeset/chilly-weeks-know.md, models/business-unit/src/company/builder.spec.ts, models/business-unit/src/company/generator.ts, models/business-unit/src/company/transformers.ts, models/business-unit/src/division/builder.spec.ts, models/business-unit/src/division/generator.ts, models/business-unit/src/division/transformers.ts
This PR adds missing inheritedStores field to the generator of Company and Division according to the new SDK (in the default and rest and graphql transformers)
=> chore(business-unit): add inheritedStores field to Company and Division models

.changeset/clever-mayflies-joke.md, .changeset/strange-hounds-shout.md, models/cart-discount/src/cart-discount-pattern-target/builders.spec.ts, models/cart-discount/src/cart-discount-pattern-target/src/cart-discount-pattern-target-draft/builders.spec.ts, models/cart-discount/src/count-on-custom-line-item-units/builders.spec.ts, models/cart-discount/src/count-on-custom-line-item-units/fields-config.ts, models/cart-discount/src/count-on-custom-line-item-units/src/count-on-custom-line-item-units-draft/builders.spec.ts, models/cart-discount/src/count-on-custom-line-item-units/src/count-on-custom-line-item-units-draft/builders.ts, models/cart-discount/src/count-on-custom-line-item-units/src/count-on-custom-line-item-units-draft/fields-config.ts, models/cart-discount/src/count-on-custom-line-item-units/src/count-on-custom-line-item-units-draft/types.ts, models/cart-discount/src/count-on-custom-line-item-units/types.ts, models/cart-discount/src/count-on-line-item-units/builders.spec.ts, models/cart-discount/src/count-on-line-item-units/fields-config.ts, models/cart-discount/src/count-on-line-item-units/src/count-on-line-item-units-draft/builders.spec.ts, models/cart-discount/src/count-on-line-item-units/src/count-on-line-item-units-draft/builders.ts, models/cart-discount/src/count-on-line-item-units/src/count-on-line-item-units-draft/fields-config.ts, models/cart-discount/src/count-on-line-item-units/src/count-on-line-item-units-draft/types.ts, models/cart-discount/src/count-on-line-item-units/types.ts
excludeCount property has been deprecated and should be removed from all our cart discount related models
=> Prc 3957 update the cart discount test data model to reflect the removal of exclude

.github/CODEOWNERS
We noticed one of the rules configured in the `CODEOWNERS` file does not seem to be working:
```
/models @commercetools/merchant-center-tech-leadership @commercetools/test-automation-engineers
```
We think it might be because of a missing trailing slash so we're introducing it in this PR.
Thanks @tdeekens for the suggestion 🙇
=> Fix codeowners rule

.changeset/odd-eggs-change.md, models/product/src/product/fields-config.ts, models/product/src/product/presets/boring-generic-milk.spec.ts, models/product/src/product/presets/boring-generic-milk.ts, models/product/src/product/presets/happy-cow-milk.spec.ts, models/product/src/product/presets/happy-cow-milk.ts
We had a bug in the `Product` compatibility presets where they were always returning a GraphQL value for the `productType` property even when the consumer wanted to build a REST `Product`.
=> Fix Product test data model compatibility presets

.changeset/bright-walls-drop.md, models/product/README.md, models/product/src/index.ts, models/product/src/product-catalog-data/index.ts, models/product/src/product-data/category-order-hint/builders.spec.ts, models/product/src/product-data/category-order-hint/index.ts, models/product/src/product-data/index.ts, models/product/src/product-data/search-keyword/builders.spec.ts, models/product/src/product-data/search-keyword/index.ts, models/product/src/product-data/search-keywords/builders.spec.ts, models/product/src/product-data/search-keywords/index.ts
We have an issue with the way we export some of the models in the `@commercetools-test-data/product` package coming from a recent migration.
This kind of imports:
```
import { ProductCatalogData } from '@commercetools-test-data/product';
```
do not work as we're namespacing those models twice.
Consumers would need to do something like this:
```
import { ProductCatalogData } from '@commercetools-test-data/product';
const model = ProductCatalogData.ProductCatalogData.random().build();
```
In this PR we're fixing the exports and also updating the README to reflect the new GraphQL and REST models.
=> Fix Product model exports

scripts/transform-imports.mjs
To keep things as simple as possible, we don't really need to have a proper codemod with AST parsing.
At the end of the day, it's a simple find and replace.
We can copy the script as-is in the repository that we want to run it for, the execute it (optionally providing a specific folder path).
=> FEC-183 - Add codemod script to migrate imports

.changeset/twelve-mangos-move.md, standalone/src/models/cart/discount-on-total-price/builders.spec.ts, standalone/src/models/cart/discount-on-total-price/builders.ts, standalone/src/models/cart/discount-on-total-price/fields-config.ts, standalone/src/models/cart/discount-on-total-price/index.ts, standalone/src/models/cart/discount-on-total-price/presets/index.ts, standalone/src/models/cart/discount-on-total-price/types.ts, standalone/src/models/cart/discounted-total-price-portion/builders.spec.ts, standalone/src/models/cart/discounted-total-price-portion/builders.ts, standalone/src/models/cart/discounted-total-price-portion/fields-config.ts, standalone/src/models/cart/discounted-total-price-portion/index.ts, standalone/src/models/cart/discounted-total-price-portion/presets/index.ts, standalone/src/models/cart/discounted-total-price-portion/types.ts, standalone/src/models/cart/index.ts
Summary :  Migrating DiscountOnTotalPrice  & DiscountedTotalPricePortion to new model
https://commercetools.atlassian.net/browse/FEC-241
Documentation
https://docs.commercetools.com/api/projects/carts#discountontotalprice
https://docs.commercetools.com/api/projects/carts#discountedtotalpriceportion
=> FEC-241 : Migrate DiscountOnTotalPrice & DiscountedTotalPricePortion to use new model

.changeset/twelve-mangos-move.md
We've incorrectly used a `major` version in a committed changeset so we're adjusting it in this PR.
=> Adjust changeset version

.changeset/chubby-seas-shop.md, standalone/src/models/product/product/index.ts
We accidentally removed the `ProductType` test data model Typescript types from the `@commercetools/composable-commerce-test-data/product` entry point (reference #847).
We're adding them back here.
=> Add missing Typescript types

.changeset/forty-carrots-check.md, standalone/src/models/product/product/index.ts, standalone/src/models/product/product/product-variant-availability/builders.spec.ts, standalone/src/models/product/product/product-variant-availability/builders.ts, standalone/src/models/product/product/product-variant-availability/fields-config.ts, standalone/src/models/product/product/product-variant-availability/index.ts, standalone/src/models/product/product/product-variant-availability/presets/index.ts, standalone/src/models/product/product/product-variant-availability/types.ts
We're introducing a new model named `ProductVariantAvailability` that can be consumed from the `@commercetools/composable-commerce-test-data/product` entry point.
This is how the new model could be used:
```ts
import { ProductVariantAvailabilityGraphql } from '@commercetools/composable-commerce-test-data/product';
const model = ProductVariantAvailabilityGraphql.random().build();
```
=> New ProductVariantAvailability test data model

standalone/src/models/product-type/attribute-definition/attribute-definition-draft/builders.spec.ts, standalone/src/models/product-type/attribute-definition/attribute-definition-draft/fields-config.ts
When working in moving the `Product` model sample data presets I noticed an issue in the `AttributeDefinitionDraft` model when trying to build a GraphQL object with the compatibility builder.
If the attribute type was of type `SimpleAttributeTypeDraft`:
```
{
dummy: String
}
```
it was not generating the right type value.
We needed to adjust the order of the checks we do in the `postBuild` config callback.
I also added some more tests to verify the update.
=> Adjust AttributeDefinition post-build function

.changeset/fuzzy-mails-dress.md, standalone/src/models/custom-fields/custom-fields/builders.spec.ts, standalone/src/models/custom-fields/custom-fields/fields-config.ts
Fixed `CustomFieldsRest` test data model as the default generated version was not populating the `fields` property but that's a required property.
Now we populate it with an empty object.
=> Fix CustomFieldsRest test data model

.changeset/orange-results-hang.md, standalone/src/models/cart/cart/index.ts, standalone/src/models/cart/cart/item-state/builders.spec.ts, standalone/src/models/cart/cart/item-state/builders.ts, standalone/src/models/cart/cart/item-state/fields-config.ts, standalone/src/models/cart/cart/item-state/index.ts, standalone/src/models/cart/cart/item-state/presets/index.ts, standalone/src/models/cart/cart/item-state/types.ts
We're introducing a new test data model named `ItemState` which can be consumed from the `@commercetools/composable-commerce-test-data/cart` entry point.
[Here](https://docs.commercetools.com/api/projects/carts#itemstate) are the official docs for this resource.
This is how it can be used:
```ts
import {
ItemStateGraphql,
ItemStateRest,
} from '@commercetools/composable-commerce-test-data/cart';
const graphqlModel = ItemStateGraphql.random().build();
const restModel = ItemStateRest.random().build();
```
=> New ItemState test data model

package.json, pnpm-lock.yaml
The `eslint` [major update](https://github.com/commercetools/test-data/pull/737) is [breaking the lintin script](https://github.com/commercetools/test-data/actions/runs/16118822834/job/45479078042) in the repository so we want to roll it back and look at it again more closely.
=> Rollback eslint update

.changeset/quick-humans-push.md, standalone/src/models/product-type/product-type/presets/index.ts, standalone/src/models/product-type/product-type/presets/tshirt.spec.ts, standalone/src/models/product-type/product-type/presets/tshirt.ts, standalone/src/models/product/product-projection/builder.spec.ts, standalone/src/models/product/product-projection/presets/happy-cow-milk.ts, standalone/src/models/product/product/product/presets/boring-generic-milk.ts, standalone/src/models/product/product/product/presets/happy-cow-milk.ts
We're introducing a new preset in the `ProductType` test data model which should help consumers building objects.
New `tshirt` preset which populates all the model properties.
Example:
```ts
import { ProductTypeGraphql } from '@commercetools/composable-commerce-test-data/product-type';
const tshirt = ProductTypeGraphql.presets.tshirt().build();
```
=> feat(product-type): add tshirt preset

.changeset/sixty-years-travel.md, standalone/src/models/cart/cart/cart/builders.spec.ts, standalone/src/models/cart/cart/cart/fields-config.ts, standalone/src/models/cart/cart/discount-code-info/builders.spec.ts, standalone/src/models/cart/cart/discount-code-info/builders.ts, standalone/src/models/cart/cart/discount-code-info/constants.ts, standalone/src/models/cart/cart/discount-code-info/fields-config.ts, standalone/src/models/cart/cart/discount-code-info/index.ts, standalone/src/models/cart/cart/discount-code-info/presets/index.ts, standalone/src/models/cart/cart/discount-code-info/types.ts, standalone/src/models/cart/cart/index.ts
With current cart model, `discountCodes` was just array of the discount codes. But actually it should be array of `DiscountCodeInfo`. As `DiscountCodeInfo` model was not available, I have added it in this PR and also fixing cart model
=> chore: Adding discount code info model

.changeset/clear-sides-yell.md, standalone/src/models/cart/cart/discounted-line-item-portion/presets/index.ts, standalone/src/models/cart/cart/discounted-line-item-portion/presets/with-all-fields/with-all-fields.spec.ts, standalone/src/models/cart/cart/discounted-line-item-portion/presets/with-all-fields/with-all-fields.ts, standalone/src/models/cart/cart/discounted-line-item-price/presets/index.ts, standalone/src/models/cart/cart/discounted-line-item-price/presets/with-all-fields/with-all-fields.spec.ts, standalone/src/models/cart/cart/discounted-line-item-price/presets/with-all-fields/with-all-fields.ts, standalone/src/models/cart/cart/line-item/constants.ts, standalone/src/models/cart/cart/line-item/field-config.ts, standalone/src/models/cart/cart/line-item/presets/with-all-fields/with-all-fields.spec.ts, standalone/src/models/cart/cart/line-item/presets/with-all-fields/with-all-fields.ts, standalone/src/models/commons/reference/types.ts
We're introducing two new `withAllFields` presets for the `DiscountedLisItemPortion` and `DiscountedLineItemPrice` that can be used to generate objects for those models with all the fields populated.
They both accept some params which allow to provide some key values used for the nested models.
Here are some examples on how they can be used:
```ts
import {
DiscountedLineItemPriceGraphql,
DiscountedLineItemPortionGraphql,
} from '@commercetools/composable-commerce-test-data/cart';
// DiscountedLineItemPrice
// When no param is provided we will use these values
//  - currencyCode: 'EUR'
//  - target: 'lineItems'
//  - discountId: 'cart-discount-id'
const discountedLineItemPrice = DiscountedLineItemPriceGraphql.presets.withAllFields();
// With some custom params
const …
```
=> Add new presets to Cart models

.changeset/rude-kiwis-strive.md, docs/guidelines/writing-changesets.md, standalone/src/models/attribute-group/attribute-group-draft/builder.spec.ts, standalone/src/models/attribute-group/attribute-group-draft/builders.ts, standalone/src/models/attribute-group/attribute-group-draft/fields-config.ts, standalone/src/models/attribute-group/attribute-group-draft/index.ts, standalone/src/models/attribute-group/attribute-group-draft/presets/empty.spec.ts, standalone/src/models/attribute-group/attribute-group-draft/presets/empty.ts, standalone/src/models/attribute-group/attribute-group-draft/presets/index.ts, standalone/src/models/attribute-group/attribute-reference/builders.spec.ts, standalone/src/models/attribute-group/attribute-reference/builders.ts, standalone/src/models/attribute-group/attribute-reference/fields-config.ts, standalone/src/models/attribute-group/attribute-reference/index.ts, standalone/src/models/attribute-group/attribute-reference/presets/index.ts, standalone/src/models/attribute-group/attribute-reference/types.ts, standalone/src/models/attribute-group/index.ts, standalone/src/models/attribute-group/types.ts
Creates the `attribute-group-draft` model, an empty preset, and the attribute-reference(used internally).
=> FEC-239: create attribute group draft model

.changeset/olive-icons-stare.md, standalone/src/models/attribute-group/attribute-group-draft/builder.spec.ts, standalone/src/models/attribute-group/attribute-group-draft/fields-config.ts, standalone/src/models/attribute-group/index.ts
We've fixed an error in the `AttributeGroupDraft` test-data model as its name was not populated with a draft model.
Also, we've updated the entry point of the `@commercetools/composable-commerce-test-data/attribute-group` package entry point so it also exports the `AttributeReference` model.
It can be used like this:
```ts
import {
AttributeReferenceGraphql,
AttributeReferenceRest,
} from '@commercetools/composable-commerce-test-data/attribute-group';
const graphqlModel = AttributeReferenceGraphql.random().build();
const restModel = AttributeReferenceRest.random().build();
```
I want to also migrate the `AttributeGroup` test-data model as a follow-up, but on it's own PR.
=> Fix AttributeGroupDraft test-data model

.github/CODEOWNERS
This pull request makes a minor update to the `.github/CODEOWNERS` file, correcting the path assignment for the `product-selection` model to ensure the correct team is assigned ownership. Currently, the @commercetools/pdm-team-fe is wrongly being assigned instead of @commercetools/context-team-fe.
=> chore(CODEOWNERS): fix path for product-selection
